export const girls = [
  {id: 58,
    name: { en: "Mina", cn: "Mina" },
    status: "available",
    verified: true,
    location: "CBD",
    stats: {
      age: 24,
      height: "173cm",
      weight: "49kg",
      cup: "B (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/mina/1.webp",
    description: {
      en: "Graceful and exceptionally tall, Mina is a recently arrived beauty from China who graduated from an Australian university. Standing at an impressive 173cm with a slender 49kg figure, she features fair, flawless skin, mesmerizing big eyes, and a gentle voice. Available for a very limited 2-week stay in Auckland CBD, she provides high-quality companionship, professional massage, and romantic interactions including sweet kisses and double rounds.",
      cn: "最新国内空降！毕业于澳洲的高颜值美少女 Mina，拥有 173cm 的高挑模特身材，体重 49kg，皮肤白皙，眼睛明亮动人，声音极其温柔。在市区 CBD 短期逗留仅限 2 周！Mina 提供高品质的暖心相伴与专业按摩服务，包含双人洗浴、无套口、69、丝袜诱惑及两次云雨陪伴，为您打造极致放松的尊享解压时光。",
    },
    price: "$500 / 1h (VIP) · $400 / 30min",
    services: {
      en: [
        "French kiss",
        "Shower together",
        "Sensory massage",
        "69",
        "Breast massage",
        "Stockings",
        "Natural BJ",
        "2 rounds",
      ],
      cn: [
        "舌吻",
        "双人洗浴",
        "感官按摩",
        "69",
        "胸推漫游",
        "丝袜诱惑",
        "无套口",
        "做2次",
      ],
    },
    gallery: [
      "/images/girls/mina/1.webp",
      "/images/girls/mina/2.webp",
      "/images/girls/mina/3.webp",
      "/images/girls/mina/4.webp",
      "/images/girls/mina/5.webp",
      "/images/girls/mina/data1.webp",
      "/images/girls/mina/data2.webp",
    ],},
  {id: 57,
    name: { en: "Nao", cn: "奈绪" },
    status: "available",
    verified: true,
    location: "CBD",
    stats: {
      age: 19,
      height: "155cm",
      weight: "43kg",
      cup: "C",
      nationality: "Japanese",
    },
    image: "/images/girls/nao/7.webp",
    description: {
      en: "Petite, adorable, and irresistibly cute, the 19-year-old Japanese student Nao is now available part-time in CBD Auckland. Standing at just 155cm with a dainty 43kg frame and natural C-cup curves, she has big, beautiful eyes and a captivating loli-like charm. Her standard session includes deep French kissing, bareback BJ, 2 shots, oral on her (DATY), mutual oral, nipple licking, pussy slider, and shower together. An ultra-rare find — this petite student only works part-time on a short-term basis, so don't miss out!",
      cn: "🆕日本🇯🇵在读学生妹兼职！超小巧玲珑的19岁日籍萝莉奈绪，大眼睛超漂亮，甜美可爱到爆。拥有155cm、43kg的极致娇小身材，天然C罩杯饱满诱人。标准服务包含深吻、无套口、做2次、69互动、舔乳、指划及双人洗浴。超小只学生妹偶尔兼职，短期开哦，绝对不容错过的极品体验！",
    },
    price: "$400 / 1h · $350 / 45min · $300 / 30min",
    services: {
      en: [
        "Shower together",
        "Deep French Kissing",
        "Bareback BJ",
        "Oral on her (DATY)",
        "Mutual oral (69)",
        "Nipple licking",
        "Pussy slider",
        "2 shots",
        "Extra: Cum in mouth (+$50) · Cum on Face (+$100) · Photo/Video no face (+$100)",
        "Note: ⚠️ No bareback sex",
      ],
      cn: [
        "双人洗浴",
        "深吻",
        "无套口",
        "舔穴",
        "69互动",
        "舔乳",
        "指划",
        "做2次",
        "额外：口爆 (+$50) · 颜射 (+$100) · 不露脸拍照录影 (+$100)",
        "备注：⚠️ 禁止无套内射",
      ],
    },
    gallery: [
      "/images/girls/nao/1.webp",
      "/images/girls/nao/3.webp",
      "/images/girls/nao/4.webp",
      "/images/girls/nao/5.webp",
      "/images/girls/nao/6.webp",
      "/images/girls/nao/7.webp",
      "/images/girls/nao/data1.webp",
      "/images/girls/nao/data2.webp",
    ],},
  {id: 56,
    name: { en: "Atomi", cn: "Atomi" },
    status: "available",
    verified: true,
    location: "Central",
    stats: {
      age: 23,
      height: "155cm",
      weight: "43kg",
      cup: "C",
      nationality: "Japanese",
    },
    image: "/images/girls/atomi/1.webp",
    description: {
      en: "Cute, petite, and exceptionally charming, Atomi is a 23-year-old Japanese beauty now serving Central Auckland. Standing at 155cm and weighing 43kg with natural C-cup curves, she features an ultra-delicate and lovely build. Extremely gentle and compliant, her standard session includes deep French kissing, bareback BJ, 69, nipple licking, pussy sliding, and 2 shots of pure pleasure. She also offers flexible premium extras including cum on face, natural creampie, and discrete recording to customize your perfect experience.",
      cn: "日系超小只女神！23岁的日籍美眉 Atomi 拥有 155cm、43kg 的极度娇小玲珑身材，天然 C 罩杯丰满胸围。性格极为乖巧顺从，声音甜美温柔。提供包含深吻、无套口吹、69互动、乳头爱抚、阴部指划和 2 次云雨的标准满分体验。额外更支持颜射、无套不内射、无套内射以及不露脸/露脸拍摄录影等个性化定制服务，在中区为您打造极致解压的日式奢宠享受。",
    },
    price: "$360 / 1h (2 rounds) · $320 / 45min · $280 / 30min",
    services: {
      en: [
        "Shower together",
        "Deep French Kissing",
        "Bareback BJ",
        "Mutual oral (69)",
        "Nipple licking",
        "Pussy slider",
        "2 shots",
        "Extra: Cum on Face (+$100) · Natural sex (no creampie) (+$150) · Natural & Creampie (+$200) · Photo/Video no face (+$200) · Photo/Video with face (+$300)",
      ],
      cn: [
        "双人洗浴",
        "深吻",
        "无套口",
        "69互动",
        "爱抚舔乳",
        "指划漫游",
        "做2次",
        "额外：颜射 (+$100) · 无套不内射 (+$150) · 无套内射 (+$200) · 拍照录影不露脸 (+$200) · 拍照录影露脸 (+$300)",
      ],
    },
    gallery: [
      "/images/girls/atomi/1.webp",
      "/images/girls/atomi/2.webp",
      "/images/girls/atomi/3.webp",
      "/images/girls/atomi/4.webp",
      "/images/girls/atomi/5.webp",
      "/images/girls/atomi/6.webp",
      "/images/girls/atomi/7.webp",
      "/images/girls/atomi/data1.webp",
      "/images/girls/atomi/data2.webp",
    ],},
  {id: 59,
    name: { en: "Yuki", cn: "Yuki" },
    status: "available",
    verified: true,
    location: "CBD",
    stats: {
      age: "25+",
      height: "163cm",
      weight: "48kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/yuki/1.webp",
    description: {
      en: "Beautiful, charming, and highly passionate, Yuki is an exceptional companion now serving CBD Auckland. Standing at 163cm with a slender 48kg figure and full C-cup breasts, she is known for her enthusiastic service and outstanding body slide techniques. Her VIP package offers the ultimate indulgence, including double rounds, direct natural BJ, head-to-toe kissing, roleplay, and toys, ensuring an unforgettable and deeply satisfying experience.",
      cn: "热情似火、颜值出众，Yuki 现已就位市区 CBD 竭诚为您服务。她身高 163cm，体重 48kg，身姿绰约，拥有饱满的 C 罩杯。Yuki 以其无微不至的极致服务态度和精湛的“莞式”全身按摩漫游技术深受好评。升级的 $360 VIP 套餐更包含无套口吹、做 2 次、深吻、从头到脚全身亲吻、丝袜诱惑、玩具及角色扮演（Cosplay）等多项高级定制，为您开启一段无比激情的难忘欢愉时光。",
    },
    price: "$360 / 1h (VIP) · $300 / 1h · $250 / 30min",
    services: {
      en: [
        "French kiss",
        "Shower together",
        "Sensory massage",
        "69",
        "Breast/Hip slide",
        "1 round",
        "Extra: Cum on Face (+$100)",
        "VIP: Cum in mouth · Second round · Dongguan style full service · Head-to-toe kissing · Toys · Stockings · Cosplay",
      ],
      cn: [
        "接吻",
        "双人陪浴",
        "感官按摩",
        "69",
        "胸推臀推",
        "做1次",
        "额外：颜射 (+$100)",
        "VIP套餐：口爆 · 做2次 · 莞式全套服务 · 全身从头到脚亲吻 · 玩具 · 丝袜 · 角色扮演",
      ],
    },
    gallery: [
      "/images/girls/yuki/1.webp",
      "/images/girls/yuki/2.webp",
      "/images/girls/yuki/3.webp",
      "/images/girls/yuki/4.webp",
      "/images/girls/yuki/data1.webp",
      "/images/girls/yuki/data2.webp",
    ],},
  {id: 54,
    name: { en: "Yuwei", cn: "雨薇" },
    status: "leave",
    verified: true,
    location: "CBD",
    stats: {
      age: 24,
      height: "164cm",
      weight: "44kg",
      cup: "C (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/yuwei/1.webp",
    description: {
      en: "Newly arrived from China, the stunning 24-year-old Yuwei features a slim, elegant figure (164cm, 44kg) with natural C-cup breasts and beautiful long legs. Soft-spoken, exceptionally gentle, and highly skilled in providing immersive, passionate companionship. Extremely detailed sensory oil massage, shower play, direct natural BJ, and romantic interactions to help you melt away your stress and enjoy a deeply satisfying, blissful escape.",
      cn: "最新国内空降刚落地！24岁的雨薇拥有164cm、44kg的修长苗条身材，天然真奶C罩杯，皮肤白嫩，颜值极高。性格温柔如水，服务态度极其贴心。擅长全身精油按摩、水中箫、深度无套口、性感黑丝及激情互动。在市区CBD为您开启一场极尽温柔与极致享受的浪漫之旅。",
    },
    price: "$360 / 1h · $300 / 30min",
    services: {
      en: [
        "Shower together",
        "French kiss",
        "Sensory massage",
        "69",
        "Stockings",
        "Finger slide",
        "1 round",
        "Extra: Cum in mouth (+$50) · Second round (+$50) · Professional SM (+$50)",
      ],
      cn: [
        "双人陪浴",
        "舌吻",
        "感官按摩",
        "69",
        "性感黑丝",
        "指划",
        "做1次",
        "额外：口爆 (+$50) · 第二次 (+$50) · 专业SM (+$50)",
      ],
    },
    gallery: [
      "/images/girls/yuwei/1.webp",
      "/images/girls/yuwei/2.webp",
      "/images/girls/yuwei/3.webp",
      "/images/girls/yuwei/4.webp",
      "/images/girls/yuwei/5.webp",
      "/images/girls/yuwei/6.webp",
      "/images/girls/yuwei/7.webp",
      "/images/girls/yuwei/8.webp",
      "/images/girls/yuwei/data1.webp",
      "/images/girls/yuwei/data2.webp",
    ],},
  {id: 48,
    name: { en: "Baicha", cn: "小白茶" },
    status: "unavailable",
    verified: true,
    location: "CBD",
    stats: {
      age: 23,
      height: "172cm",
      weight: "45kg",
      cup: "36D+ (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/baicha/1.webp",
    video: "/images/girls/baicha/video.mp4",
    description: {
      en: "The newest Australian arrival ✈️born in 2003, super gorgeous student Baicha! High visual, absolutely stunning even bare-faced. Active fitness lover with fair, smooth, and firm skin, featuring natural 36D+ full breasts. Sweet and cute face with an incredibly sexy, passionate contrast. Extremely attentive and proactive, she loves to tease and perfectly caters to your every whim. Short stay of only 9 days in Auckland CBD — a premium experience you cannot miss!",
      cn: "最🆕澳洲空降✈️03年在读学生！超级惊艳的颜值天花板小白茶！超高颜值，素颜抗打。平时非常热爱健身，拥有白嫩紧致的完美肤色，纯天然36D+罩杯饱满柔软，吹弹可破。虽然五官甜美动人，但却有着反差极大的性感调情天赋。作为服务系女生，主动撩人，极尽迎合，让您体验百分百的温柔。短期在奥克兰CBD停留仅9天，绝对不容错过的极品体验！",
    },
    price: "$600 / 1h",
    services: {
      en: [
        "Shower together",
        "Natural BJ",
        "69",
        "French kiss",
        "Stockings",
        "Breast massage",
        "1 round",
        "Extra: Cum in mouth (+$50) · Second round negotiable",
        "Note: 1 day minimum stay, Daily/Overnight booking available ($3200-$3500 / 8-10h, $5000 / Day)",
      ],
      cn: [
        "陪浴",
        "无套口",
        "69",
        "蛇吻",
        "黑丝",
        "胸推",
        "做1次",
        "额外：口爆 (+$50) · 第二次自己商量",
        "备注：1天起租 可包过 ($3200-$3500 / 8-10h, $5000 / 天)",
      ],
    },
    gallery: [
      "/images/girls/baicha/1.webp",
      "/images/girls/baicha/2.webp",
      "/images/girls/baicha/3.webp",
      "/images/girls/baicha/4.webp",
      "/images/girls/baicha/5.webp",
      "/images/girls/baicha/6.webp",
      "/images/girls/baicha/data1.webp",
      "/images/girls/baicha/data2.webp",
    ],},
  {id: 42,
    name: { en: "Doudou", cn: "兜兜" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 22,
      height: "158cm",
      weight: "45kg",
      cup: "B+ (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/doudou/doudou1.webp",
    description: {
      en: "Limited edition 2003 model. Not very cool, but very genuine. Can be energetic, can be quiet. Might get emo but heals quickly. Wants to be someone slightly cute, a bit special, and very easy to get along with ❤️",
      cn: "03年款限量版，不是很酷，但很真，会闹腾，也会安静，会emo但更会自愈，想做一个有点可爱，有点特别，又很好相处的人❤️",
    },
    price: "$400 / 1h",
    services: {
      en: [
        "kiss",
        "69",
        "shower together",
        "stockings",
        "uniform",
        "natural bj",
        "cooperate with various poses",
        "breast massage",
        "Extra: 2nd round (+$100)",
      ],
      cn: [
        "轻吻",
        "69",
        "陪浴",
        "黑丝",
        "制服",
        "无套吹",
        "配合各种姿势",
        "胸推",
        "额外：第二次 (+$100)",
      ],
    },
    gallery: [
      "/images/girls/doudou/doudou4.webp",
      "/images/girls/doudou/doudou5.webp",
      "/images/girls/doudou/doudou2.webp",
      "/images/girls/doudou/doudou3.webp",
    ],},
  {id: 43,
    name: { en: "Susu", cn: "苏苏" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 24,
      height: "170cm",
      weight: "47kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/susu/susu1.webp",
    description: {
      en: "The newest Australian arrival ✈️ 170cm legs, model figure, fair skin and tender girl, extremely cooperative. Short stay in Auckland, what are you waiting for? Do not miss this...",
      cn: "最🆕澳洲空降✈️170足腿精，模特身材，肤白妹嫩，配合度超高。短期停留奥克兰，小哥哥还在等什么，走过路过千万不要错过...",
    },
    price: "$450 / 1h · $350 / 30min",
    services: {
      en: [
        "French kiss",
        "69",
        "rimming",
        "stockings",
        "shower together",
        "massage",
        "shower bj",
        "finger play",
        "breast massage",
        "uniform",
        "2 rounds",
        "Extra: Cum in mouth (+$100)",
      ],
      cn: [
        "轻吻",
        "69",
        "毒龙",
        "黑丝",
        "泡澡",
        "按摩",
        "水中箫",
        "指划",
        "舔蛋",
        "制服",
        "2次",
        "额外：口爆 (+$100)",
      ],
    },
    gallery: [
      "/images/girls/susu/susu2.webp",
      "/images/girls/susu/susu3.webp",
      "/images/girls/susu/susu4.webp",
      "/images/girls/susu/susu5.webp",
      "/images/girls/susu/susu6.webp",
      "/images/girls/susu/susu7.webp",
      "/images/girls/susu/susu8.webp",
    ],},
  {id: 46,
    name: { en: "Nainai", cn: "小奈奈" },
    status: "leave",
    verified: true,
    location: "CBD",
    stats: {
      age: 23,
      height: "164cm",
      weight: "44kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/nainai/nainai1.webp",
    description: {
      en: "The newest Australian arrival ✈️born in 2003, super tender young beauty Nainai! High visual, absolutely stunning even bare-faced. Active fitness lover with fair, smooth, and firm skin, featuring natural C-cup full breasts. Sweet and cute face with an incredibly sexy, passionate contrast. Extremely attentive and proactive, she loves to tease and perfectly caters to your every whim. Let's meet in the City, a premium experience you cannot miss!",
      cn: "最🆕澳洲空降✈️03年超嫩美少女小奈奈！初次来到奥克兰，颜值极高，素颜抗打。平时非常热爱健身，拥有白嫩紧致的完美肤色，纯天然C罩杯饱满柔软。虽然五官甜美动人，但却有着反差极大的性感调情天赋。作为服务系女生，主动撩人，极尽迎合，让您体验百分百的温柔。City不见不散，绝对不容错过的极品体验！",
    },
    price: "$450 / 1h · $400 / 45min · $350 / 30min",
    services: {
      en: [
        "Companionship",
        "Flirting",
        "Role play",
        "Uniform temptation",
        "Stockings",
        "Shower together",
        "Massage",
        "Shower BJ",
        "French kiss",
        "Finger glide",
        "Natural BJ",
        "Breast massage",
        "69",
        "1 round",
        "Extra: Cum in mouth (+$50) · Rimming (+$50) · Second round (+$50) · Cum on face (+$100)",
        "Note: 1 day minimum stay, Daily/Overnight booking available ($3000-$3200 / 8-10h, $4500 / Day)",
      ],
      cn: [
        "陪伴",
        "调情",
        "角色扮演",
        "制服诱惑",
        "黑丝",
        "双人洗浴",
        "按摩",
        "水中箫",
        "舌吻",
        "指滑",
        "舔蛋",
        "胸推",
        "69",
        "做1次",
        "额外：口爆 (+$50) · 毒龙 (+$50) · 第二次 (+$50) · 颜射 (+$100)",
        "备注：1天起租 可包过 ($3000-$3200 / 8-10h, $4500 / 天)",
      ],
    },
    gallery: [
      "/images/girls/nainai/nainai2.webp",
      "/images/girls/nainai/nainai3.webp",
      "/images/girls/nainai/nainai4.webp",
      "/images/girls/nainai/nainai5.webp",
      "/images/girls/nainai/nainai6.webp",
      "/images/girls/nainai/nainai7.webp",
      "/images/girls/nainai/nainai8.webp",
      "/images/girls/nainai/nainai9.webp",
      "/images/girls/nainai/nainai10.webp",
      "/images/girls/nainai/data1.webp",
      "/images/girls/nainai/data2.webp",
    ],},
  {id: 49,
    name: { en: "Luna", cn: "露娜" },
    status: "available",
    verified: true,
    location: "East",
    stats: {
      age: 24,
      height: "163cm",
      weight: "47kg",
      cup: "C (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/luna/1.webp",
    description: {
      en: "Gentle, intellectual, and sweet, the charming 24-year-old Luna is available in East Auckland. Featuring a perfect frame (163cm, 47kg) with natural C-cup curves and fair, smooth skin. An expert in custom SVIP and Full Service experiences, she is exceptionally cooperative and accommodates all of your desires. From relaxing shower sessions, French kissing, and body slide to high-passion natural BJ and multi shots, she ensures an unforgettable, deeply relaxing escape.",
      cn: "温柔如水、知性迷人的24岁女孩露娜，现已来到东区为您提供高端贴心陪伴。她拥有163cm、47kg的匀称娇躯，天然C罩杯性感曲线与白嫩肌肤，服务态度超群，配合度极高。专业定制SVIP与全套互动体验，包含双人淋浴、缠绵舌吻、性感黑丝、胸推漫游、深度无套口及口爆等项目。在东区舒适安逸的环境中，为您呈现极尽缠绵与彻底放松的感官享受。",
    },
    price: "$320 / 1h (VIP) · $240 / 1h · $200 / 30min",
    services: {
      en: [
        "French kiss",
        "Shower together",
        "Sensory massage",
        "69",
        "Body slide",
        "Natural BJ",
        "Multi shots",
        "VIP: Natural BJ · French kiss · 69 · Cum in mouth · Multi shots · Shower together · Body slide",
      ],
      cn: [
        "舌吻",
        "双人洗浴",
        "感官按摩",
        "69",
        "胸推漫游",
        "无套口",
        "多次数",
        "VIP套餐：无套口 · 舌吻 · 69 · 口爆 · 多次数 · 双人洗浴 · 胸推漫游",
      ],
    },
    gallery: [
      "/images/girls/luna/2.webp",
      "/images/girls/luna/3.webp",
      "/images/girls/luna/data1.webp",
      "/images/girls/luna/data2.webp",
    ],},
  {id: 50,
    name: { en: "Annie", cn: "安妮" },
    status: "available",
    verified: true,
    location: "Central",
    stats: {
      age: 24,
      height: "163cm",
      weight: "47kg",
      cup: "C (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/annie/1.webp",
    description: {
      en: "Petite, sweet, and incredibly gentle, the charming 24-year-old Annie is now available in Central to offer you her dedicated companionship. Blessed with a natural C-cup bust and a beautiful petite frame (163cm, 47kg), she has a warming gaze and a deeply nurturing personality. Specializing in both gentle sensory massage and high-passion intimate SVIP/Full Service packages, she focuses on every detail to satisfy your every desire and ensure a deeply relaxing, blissful escape.",
      cn: "娇小玲珑、温柔甜美的24岁女孩安妮，现已来到中区为您提供专属的温存陪伴。她拥有自然丰满的C罩杯和纤细均衡的娇俏身材（163cm，47kg），眼神温柔，服务周到。专业定制SVIP与全套互动体验，包含双人淋浴、缠绵舌吻、性感黑丝、胸推漫游、深度无套口及口爆等项目。在温馨舒适的环境中，为您呈现极尽缠绵与彻底放松的感官享受。",
    },
    price: "$320 / 1h (VIP) · $240 / 1h · $200 / 30min",
    services: {
      en: [
        "French kiss",
        "Shower together",
        "Sensory massage",
        "69",
        "Body slide",
        "Natural BJ",
        "Multi shots",
        "VIP: Natural BJ · French kiss · 69 · Cum in mouth · Multi shots · Shower together · Body slide",
      ],
      cn: [
        "舌吻",
        "双人洗浴",
        "感官按摩",
        "69",
        "胸推漫游",
        "无套口",
        "多次数",
        "VIP套餐：无套口 · 舌吻 · 69 · 口爆 · 多次数 · 双人洗浴 · 胸推漫游",
      ],
    },
    gallery: [
      "/images/girls/annie/2.webp",
      "/images/girls/annie/data1.webp",
      "/images/girls/annie/data2.webp",
    ],},
  {id: 51,
    name: { en: "Nina", cn: "妮娜" },
    status: "available",
    verified: true,
    location: "East",
    stats: {
      age: 24,
      height: "163cm",
      weight: "47kg",
      cup: "C (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/nina/1.webp",
    description: {
      en: "Elegant, charming, and deeply attentive, the beautiful 24-year-old Nina is now available in East Auckland to offer you a highly tailored, intimate encounter. Standing at 163cm with a perfectly balanced natural C-cup figure and fair, smooth skin. Specializing in both gentle sensory massage and high-passion intimate SVIP/Full Service packages, she focuses on every detail to satisfy your every desire and ensure a deeply relaxing, blissful escape.",
      cn: "优雅迷人、温婉贴心的24岁女孩妮娜，现已在奥克兰东区为您开启专属的私密邂逅。她拥有163cm、47kg的匀称娇躯，天然丰满的C罩杯极具诱惑，配合度无与伦比。专业定制SVIP与全套互动体验，包含双人淋浴、缠绵舌吻、性感黑丝、胸推漫游、深度无套口及口爆等项目。在东区舒适安逸的环境中，为您呈现极尽缠绵与彻底放松的感官享受。",
    },
    price: "$320 / 1h (VIP) · $240 / 1h · $200 / 30min",
    services: {
      en: [
        "French kiss",
        "Shower together",
        "Sensory massage",
        "69",
        "Body slide",
        "Natural BJ",
        "Multi shots",
        "VIP: Natural BJ · French kiss · 69 · Cum in mouth · Multi shots · Shower together · Body slide",
      ],
      cn: [
        "舌吻",
        "双人洗浴",
        "感官按摩",
        "69",
        "胸推漫游",
        "无套口",
        "多次数",
        "VIP套餐：无套口 · 舌吻 · 69 · 口爆 · 多次数 · 双人洗浴 · 胸推漫游",
      ],
    },
    gallery: [
      "/images/girls/nina/2.webp",
      "/images/girls/nina/data1.webp",
      "/images/girls/nina/data2.webp",
    ],},
  {id: 52,
    name: { en: "Xiaxia", cn: "夏夏" },
    status: "available",
    verified: true,
    location: "East",
    stats: {
      age: 24,
      height: "163cm",
      weight: "47kg",
      cup: "C (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/xiaxia/1.webp",
    description: {
      en: "Brimming with youthful energy and sweet charm, the beautiful 24-year-old Xiaxia is now available in East Auckland to offer you a highly tailored, intimate encounter. Standing at 163cm with a perfectly balanced natural C-cup figure and fair, smooth skin. Specializing in both gentle sensory massage and high-passion intimate SVIP/Full Service packages, she focuses on every detail to satisfy your every desire and ensure a deeply relaxing, blissful escape.",
      cn: "青春洋溢、甜美迷人的24岁女孩夏夏，现已在奥克兰东区为您开启专属的私密邂逅。她拥有163cm、47kg的匀称娇躯，天然丰满的C罩杯极具诱惑，配合度无与伦比。专业定制SVIP与全套互动体验，包含双人淋浴、缠绵舌吻、性感黑丝、胸推漫游、深度无套口及口爆等项目。在东区舒适安逸的环境中，为您呈现极尽缠绵与彻底放松的感官享受。",
    },
    price: "$320 / 1h (VIP) · $240 / 1h · $200 / 30min",
    services: {
      en: [
        "French kiss",
        "Shower together",
        "Sensory massage",
        "69",
        "Body slide",
        "Natural BJ",
        "Multi shots",
        "VIP: Natural BJ · French kiss · 69 · Cum in mouth · Multi shots · Shower together · Body slide",
      ],
      cn: [
        "舌吻",
        "双人洗浴",
        "感官按摩",
        "69",
        "胸推漫游",
        "无套口",
        "多次数",
        "VIP套餐：无套口 · 舌吻 · 69 · 口爆 · 多次数 · 双人洗浴 · 胸推漫游",
      ],
    },
    gallery: [
      "/images/girls/xiaxia/2.webp",
      "/images/girls/xiaxia/3.webp",
      "/images/girls/xiaxia/data1.webp",
      "/images/girls/xiaxia/data2.webp",
    ],},
  {id: 53,
    name: { en: "Blind Box 2", cn: "盲盒2" },
    status: "available",
    verified: true,
    location: "CBD",
    stats: {
      height: "Varies",
      weight: "Varies",
      cup: "Varies",
      nationality: "Chinese",
    },
    image: "/images/girls/blindbox2/1.webp",
    description: {
      en: "Unveil the excitement of Blind Box 2! For a flat rate of $360 per hour, you'll be paired with a stunning surprise beauty in CBD Auckland. This premium package features an ultra-satisfying sensory experience including shower together, passionate French kissing, relaxing massage, intimate 69, sexy stockings, and 1 complete round of pure bliss, plus premium options like natural BJ and oral finish. High value, intense passion, and unforgettable moments in the CBD!",
      cn: "开启心动盲盒2号惊喜！仅需 $360 特惠价，为您解锁市区CBD的一位高端宝藏女孩。特惠体验包含双人陪浴、深度无套口、口爆、贴心69、缠绵舌吻、性感黑丝、感官精油按摩及完整 1 次云雨。在CBD温馨舒适的私密空间中，尽享超值与反差的极致浪漫与极致激情！",
    },
    price: "$360 / 1h",
    services: {
      en: [
        "Shower together",
        "French kiss",
        "Sensory massage",
        "69",
        "Stockings",
        "1 round",
        "Extra: Natural BJ (+$30) · Cum in mouth (+$50) · Second round (+$50)",
      ],
      cn: [
        "陪浴",
        "舌吻",
        "感官按摩",
        "69",
        "黑丝",
        "做1次",
        "额外：无套口 (+$30) · 口爆 (+$50) · 第二次 (+$50)",
      ],
    },
    gallery: [
      "/images/girls/blindbox2/1.webp",
    ],},
  {id: 39,
    name: { en: "Aozora Hikari", cn: "青空光" },
    status: "hidden",
    verified: true,
    location: "Central",
    stats: {
      age: 24,
      height: "169cm",
      weight: "52kg",
      cup: "DD",
      nationality: "Japanese",
    },
    image: "/images/girls/hikari/1.webp",
    description: {
      en: "Newly arrived Japanese beauty Aozora Hikari (born 2002). A stunning, gentle, and highly anticipated arrival, offering a premium and highly customizable experience.",
      cn: "🆕最新日本空降🌸 中区：青空光（02年），超高颜值，甜美可爱，服务温柔细致，提供高品质多样化互动体验。",
    },
    price: "$380 / 1h · $320 / 45min · $280 / 30min",
    services: {
      en: [
        "Shower\u00A0together",
        "Light\u00A0kiss",
        "Natural\u00A0bj",
        "69",
        "2\u00A0shots",
        "Extra: Facial(+$100) Bareback(+$150) Bareback\u00A0finish(+$200) Discreet\u00A0Photo/Video(+$200) Photo/Video\u00A0with\u00A0face(+$300) SM(+$200: Golden\u00A0shower/Swallow/Whipping/Choking/Hair\u00A0pulling/Spanking/Deep\u00A0throat/French\u00A0kiss/Toys)",
      ],
      cn: [
        "洗澡",
        "轻吻",
        "无套口",
        "69",
        "做2次",
        "额外：颜射(+$100) 无套(+$150) 无套内射(+$200) 不露脸拍照(+$200) 露脸拍照(+$300) SM(+$200:黄金表演/吞咽/鞭打/掐脖/扯发/拍打/深喉/蛇吻/玩具等)",
      ],
    },
    gallery: [
      "/images/girls/hikari/1.webp",
      "/images/girls/hikari/2.webp",
      "/images/girls/hikari/3.webp",
      "/images/girls/hikari/4.webp",
      "/images/girls/hikari/5.webp",
      "/images/girls/hikari/6.webp",
      "/images/girls/hikari/7.webp",
      "/images/girls/hikari/8.webp",
      "/images/girls/hikari/data1.webp",
      "/images/girls/hikari/data2.webp",
    ],},
  {id: 47,
    name: { en: "Blind Box 3", cn: "盲盒3" },
    status: "leave",
    verified: true,
    location: "CBD",
    stats: {
      age: 24,
      height: "163cm",
      weight: "47kg",
      cup: "D",
      nationality: "Chinese",
    },
    image: "/images/girls/blindbox3/1.webp",
    description: {
      en: "Experience the ultimate excitement with Blind Box 3! For a flat rate of $340, enjoy a premium 1-hour session featuring a beautiful 24-year-old treasure with a perfect 163cm, 47kg frame and natural D-cup curves. The package includes double the pleasure with 2 full rounds, relaxing shower play, direct natural BJ, intimate 69, stockings, and premium oral finishing. High value, intense passion, and unforgettable moments in the CBD!",
      cn: "开启心动盲盒3号惊喜！仅需 $340 特惠价，为您解锁一位 24岁、身高163cm、体重47kg、拥有天然D罩杯性感曲线的市区高端宝藏女孩。特惠体验包含双人洗浴、深度无套口、69互动、性感黑丝、激情口报以及毒龙服务，更承诺整整 2 次云雨体验。在CBD温馨舒适的私密空间中，尽享超值与反差的极致激情！",
    },
    price: "$340 / Special Package (2 rounds)",
    services: {
      en: [
        "Shower together",
        "Natural BJ",
        "69",
        "Stockings",
        "Cum in mouth",
        "Rimming",
        "2 rounds",
      ],
      cn: [
        "陪浴",
        "无套口",
        "69",
        "黑丝",
        "口报",
        "毒龙",
        "做2次",
      ],
    },
    gallery: [
      "/images/girls/blindbox3/1.webp",
    ],},
  {id: 45,
    name: { en: "Sweetie", cn: "甜心" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 24,
      height: "165cm",
      weight: "46kg",
      cup: "G",
      nationality: "Chinese",
    },
    image: "/images/girls/tianxin/tianxin1.webp",
    description: {
      en: "A sweet little angel featuring a breathtaking G-cup figure and a sweet, captivating doll-like face. Incredibly gentle, friendly, and highly cooperative, she is dedicated to fulfilling all your desires for intimacy and interaction. Supports mild S/M roleplay (as M, accepts light face/breast slapping, spanking, choking, and verbal dirty talk), ensuring an unforgettable night of dual passion and ultimate satisfaction.",
      cn: "天使小可爱，拥有傲人的G罩杯魔鬼身材与甜美迷人的天使面容。性格极其温顺软萌，配合度极高，可满足您对温柔和互动的全部幻想。支持轻度S或M角色扮演（女生做M接受轻微扇耳光、扇胸部、打屁股、掐脖子、言语辱骂等），让您体验极致的温柔与双向奔赴的狂野体验。",
    },
    price: "$400 / 1h (2 rounds) · $320 / 1h (1 round)",
    services: {
      en: [
        "Companionship",
        "Flirting",
        "Role play",
        "Uniform",
        "Stockings",
        "Shower together",
        "Breast massage",
        "Soft kiss",
        "BJ",
        "Body slide",
        "1 round",
        "VIP: Companionship, Shower together, Shower BJ, French kiss, Breast massage, 69, Finger glide, Body slide, Roaming, Uniform temptation, Natural BJ, Stockings, 2 rounds, Light S/M support",
        "Extra: French kiss (+$30), Natural BJ (+$30), Cum in mouth (+$50), Second round (+$50)",
      ],
      cn: [
        "陪伴",
        "调情",
        "角色扮演",
        "制服",
        "丝袜",
        "双人洗浴",
        "胸推",
        "轻吻",
        "吹箫",
        "臀推",
        "做1次",
        "VIP: 陪伴、水中箫、舌吻、胸推、69、指滑、臀推、漫游、制服诱惑、无套口、黑丝、配合各种姿势、做2次、可轻微S/M",
        "额外：舌吻 (+$30)，无套口(+$30)，口爆(+$50)，做第二次 (+$50)",
      ],
    },
    gallery: [
      "/images/girls/tianxin/tianxin2.webp",
      "/images/girls/tianxin/tianxin3.webp",
      "/images/girls/tianxin/tianxin4.webp",
      "/images/girls/tianxin/tianxin5.webp",
      "/images/girls/tianxin/tianxin6.webp",
      "/images/girls/tianxin/tianxin7.webp",
    ],},
  {id: 44,
    name: { en: "Rourou", cn: "肉肉" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 21,
      height: "164cm",
      weight: "45kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/rourou/rourou1.webp",
    description: {
      en: "A stunning 2003-born beauty with a mature royal sister vibe. Featuring a perfect A4 waist, beautifully-shaped breasts, and exceptionally firm skin, her soft, soothing voice and sweet smile will instantly melt you away.",
      cn: "03年御姐型，A4腰，胸型恰到好处，肌肤紧实，加上细软的嗓音，甜甜的笑容让你瞬间融化。",
    },
    price: "$360 / 1h (2 rounds) · $280 / 1h (1 round)",
    services: {
      en: [
        "Companionship",
        "Flirting",
        "Role play",
        "Uniform",
        "Stockings",
        "1 round",
        "VIP: Companionship, Shower BJ, French kiss, Breast massage, 69, Finger glide, Body slide, Roaming, Uniform temptation, Licking eggs, Stockings, 2 rounds",
      ],
      cn: [
        "陪伴",
        "调情",
        "角色扮演",
        "制服",
        "丝袜",
        "做1次",
        "VIP: 陪伴、水中箫、舌吻、胸推、69、指滑、臀推、漫游、制服诱惑、舔蛋、黑丝、做2次",
      ],
    },
    gallery: [
      "/images/girls/rourou/rourou2.webp",
      "/images/girls/rourou/rourou3.webp",
      "/images/girls/rourou/rourou4.webp",
      "/images/girls/rourou/rourou5.webp",
      "/images/girls/rourou/rourou6.webp",
    ],},
  {id: 41,
    name: { en: "Sweetie", cn: "小甜心" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 19,
      height: "164cm",
      weight: "45kg",
      cup: "B+ (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/sweetie/1.webp",
    description: {
      en: "Newly arrived student Sweetie (born 2006), a radiant young beauty with stunning looks even without makeup. Standing at 164cm with a natural B+ cup, she is energetic, loves singing, dancing, and fitness. Her bubbly, healing personality and youthful charm create an unforgettable contrast. Highly cooperative with amazing service. Ultra short-term stay of only 5 days — don't miss out!",
      cn: "最🆕澳洲空降🪂小甜心06年学生👩‍🎓，超短期停留5️⃣天，小哥哥还在等什么走过路过千万不要错过...😘😘\\n🧢超过颜值 素颜抗打 雅思四个7\\n🍭能歌善舞，舞动多姿 也爱健身💪，特别是爱笑的性格超级治愈\\n这种年龄小又能给你反差的sao 真不多了🤩🎉\\n😱 偏M属性 这个06年绝对有服务会配合有服务 …不见不散💋😘",
    },
    price: "$600 / 1h · $500 / 45min · $400 / 30min",
    services: {
      en: [
        "Natural\u00A0bj",
        "69",
        "French\u00A0kiss",
        "stockings",
        "breast\u00A0massage",
        "massage",
        "Submarine\u00A0bj",
        "finger\u00A0glide",
        "licking\u00A0eggs",
        "2\u00A0shots",
      ],
      cn: [
        "无套口",
        "69",
        "舌吻",
        "黑丝",
        "胸推",
        "按摩",
        "水中箫",
        "指滑",
        "舔蛋",
        "做2次",
      ],
    },
    gallery: [
      "/images/girls/sweetie/2.webp",
      "/images/girls/sweetie/3.webp",
      "/images/girls/sweetie/4.webp",
      "/images/girls/sweetie/5.webp",
      "/images/girls/sweetie/6.webp",
      "/images/girls/sweetie/data1.webp",
      "/images/girls/sweetie/data2.webp",
    ],},
  {id: 28,
    name: { en: "Qinger", cn: "情儿" },
    status: "available",
    verified: true,
    location: "CBD",
    stats: {
      age: 24,
      height: "160cm",
      weight: "45kg",
      cup: "B+",
      nationality: "Chinese",
    },
    image: "/images/girls/qinger/1.webp",
    description: {
      en: "Charming and attentive, Qinger brings a soft and sensual energy to her sessions in CBD Auckland. Standing at 160cm with a delicate build, she specializes in therapeutic and sensual massage, focusing on relaxation and high-quality interaction. Her gentle nature and careful service make her a favorite for those seeking a more personal and soothing experience. Available for both standard sessions and extended premium interactions with additional oral and sensory options.",
      cn: "温柔体贴，服务至上，让您在繁忙的城市中找到那份宁静与欢愉。情儿现已来到市区CBD，为您提供最专业的身心呵护。主要提供按摩和感官互动服务。额外的标准互动均可配合。",
    },
    price: "$160 / 1h",
    services: {
      en: [
        "Sensual\u00A0massage",
        "HJ\u00A0(condom)",
        "Topless",
        "Handjob",
        "Extra: Natural\u00A0BJ\u00A0(+$50) Natural\u00A0BJ\u00A0&\u00A0cim\u00A0in\u00A0mouth\u00A0(+$80)",
      ],
      cn: [
        "按摩",
        "带套口",
        "裸上身",
        "飞机",
        "额外：无套口(+$50) 无套口&口报(+$80)",
      ],
    },
    gallery: [
      "/images/girls/qinger/1.webp",
      "/images/girls/qinger/2.webp",
      "/images/girls/qinger/3.webp",
      "/images/girls/qinger/4.webp",
      "/images/girls/qinger/5.webp",
      "/images/girls/qinger/6.webp",
    ],},
  {id: 37,
    name: { en: "Maimai", cn: "麦麦" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 19,
      height: "173cm",
      weight: "45kg",
      cup: "C (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/maimai/1.webp",
    description: {
      en: "Newly arrived student from Xiamen, Maimai is the 'White Moonlight' of your dreams. Standing at 173cm with a perfect model frame and natural C-cup features, she offers a pure, innocent yet incredibly sweet encounter. Her service is active, highly engaging, and full of that 'first love' charm. Short term stay until May 16th.",
      cn: "🆕厦门在读大三学生麦麦，初次登场AKL！\n🌟你的白月光、初恋遗憾，超高颜值，素颜抗打\n👗清纯可爱迷人，衣服架子身材，服务主动配合，带入感极强\n💖初下海不久，超甜反差纯白水，短期停留5月16号回国",
    },
    price: "$500 / 1h · $400 / 30min · $800 / 90min",
    services: {
      en: [
        "Natural\u00A0bj",
        "shower\u00A0together",
        "Light\u00A0kiss",
        "stockings",
        "breast\u00A0massage",
        "water\u00A0bj",
        "finger\u00A0glide",
        "licking\u00A0eggs",
        "1\u00A0shot",
      ],
      cn: [
        "无套口",
        "鸳鸯浴",
        "轻轻吻",
        "黑丝",
        "指滑",
        "按摩",
        "水中箫",
        "添蛋",
        "做1次",
      ],
    },
    gallery: [
      "/images/girls/maimai/2.webp",
      "/images/girls/maimai/3.webp",
      "/images/girls/maimai/4.webp",
      "/images/girls/maimai/5.webp",
      "/images/girls/maimai/6.webp",
      "/images/girls/maimai/7.webp",
      "/images/girls/maimai/8.webp",
      "/images/girls/maimai/data1.webp",
      "/images/girls/maimai/data2.webp",
    ],},
  {id: 1,
    name: { en: "Jinxi", cn: "锦汐" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 24,
      height: "171cm",
      weight: "48kg",
      cup: "C+ (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/jinxi/1.webp",
    video: "/images/girls/jinxi/video.mp4",
    description: {
      en: "Elegance meets sophistication in Auckland CBD with Jinxi. Standing tall at 171cm with a slender model frame and natural C+ features, she offers an exceptionally refined and immersive experience. Specializing in high-end, diverse techniques and playful roleplay, she brings a premium touch to every interaction. Perfectly bilingual and highly professional, she ensures every visit is memorable, discreet, and deeply satisfying.",
      cn: "锦汐，24岁，身高171cm，体重48kg，自然C+杯。模特身材，气质出众。现已在奥克兰市区就位，为您提供最专业、最贴心的的高端体验。擅长法式热吻、角色扮演、冰火两重天等多种精品服务，配合度极高。支持S&M等特殊定制，让您在繁华市区享受难忘的温柔时光。",
    },
    price: "$400 / 1h · $350 / 30min · $700 / 90min · $800 / 2h",
    services: {
      en: [
        "shower\u00A0together",
        "Natural\u00A0bj",
        "69",
        "Water\u00A0bj",
        "Roleplay",
        "Ice\u00A0&\u00A0Fire",
        "French\u00A0kiss",
        "Breast\u00A0massage",
        "Dragon\u00A0techniques",
        "Deep\u00A0throat",
        "Swivel\u00A0Dragon",
        "Inverted\u00A0Dragon",
        "Thai\u00A0massage",
        "Body\u00A0massage",
        "Stockings",
        "Uniform",
        "3P",
        "1\u00A0shot",
        "Extra: Rimming(+$50) CIM(+$50) 2nd\u00A0shot(+$50) Discreet\u00A0Photo/Video(+$100) Face\u00A0CIM(+$100) S&M(+$100+) No\u00A0raw\u00A0sex No\u00A0alcohol",
      ],
      cn: [
        "陪浴",
        "无套口",
        "69",
        "水中箫",
        "角色扮演",
        "冰火两重天",
        "法式kiss",
        "胸推",
        "箫摇摆龙",
        "深喉龙",
        "旋转龙",
        "倒挂金钩龙",
        "泰式抓龙筋",
        "按摩",
        "黑丝高跟",
        "制服诱惑",
        "3P",
        "做1次",
        "额外：毒龙(+$50) 口报(+$50) 第二次(+$50) 不露脸拍照录影(+$100) 颜射(+$100, 当天最后一个) S&M(+$100起) 禁无套 禁酒后",
      ],
    },
    gallery: [
      "/images/girls/jinxi/1.webp",
      "/images/girls/jinxi/2.webp",
      "/images/girls/jinxi/3.webp",
      "/images/girls/jinxi/4.webp",
      "/images/girls/jinxi/5.webp",
      "/images/girls/jinxi/data1.webp",
      "/images/girls/jinxi/data2.webp",
    ],},
  {id: 2,
    name: { en: "Qingbao", cn: "晴宝" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 24,
      height: "170cm",
      weight: "46kg",
      cup: "E",
      nationality: "Taiwanese",
    },
    image: "/images/girls/qingbao/1.webp",
    video: "/images/girls/qingbao/video.mp4",
    description: {
      en: "Pure sweetness from Taiwan, Qingbao makes her first appearance in Auckland, bringing a delightful blend of innocence and allure. Newly arrived, she features an incredible natural E-cup figure on a slender 46kg frame. With her sweet personality, big eyes, and charming Taiwanese accent, she provides an attentive and deeply immersive service quality. Ideal for those seeking a premium encounter with a companion who is both elegant and incredibly sweet, she is only here for a short stay.",
      cn: "台湾空降🪂 台湾影视学院晴宝初次登场AKL 高颜值童颜巨ru声音高颜值大眼睛超甜 服务主动 带入感很强、纯天E🥛大🐻大pi古 前凸后翘气质文雅 长相御姐 声音台湾腔嗲嗲酥酥超甜的反差纯白水🎉 短期停留",
    },
    price: "$500 / 1h · $400 / 30min",
    services: {
      en: [
        "Natural\u00A0bj",
        "shower\u00A0together",
        "69",
        "French\u00A0kiss",
        "stockings",
        "Submarine\u00A0bj",
        "Licking\u00A0eggs",
        "shower",
        "2\u00A0shots",
      ],
      cn: [
        "无套口",
        "陪浴",
        "69",
        "舌吻",
        "黑丝",
        "水中箫",
        "舔蛋",
        "淋浴",
        "做2次",
      ],
    },
    gallery: [
      "/images/girls/qingbao/1.webp",
      "/images/girls/qingbao/2.webp",
      "/images/girls/qingbao/3.webp",
      "/images/girls/qingbao/4.webp",
      "/images/girls/qingbao/5.webp",
      "/images/girls/qingbao/6.webp",
      "/images/girls/qingbao/7.webp",
      "/images/girls/qingbao/8.webp",
      "/images/girls/qingbao/9.webp",
    ],},
  {id: 6,
    name: { en: "CC", cn: "CC" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 23,
      height: "160cm",
      weight: "45kg",
      cup: "C+ (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/cc/1.webp",
    video: "/images/girls/cc/video.mp4",
    description: {
      en: "CC (born in 2003), is an elegant and refined beauty. Standing at 160cm with a natural C+ cup, she offers a wide spectrum of services from intimate companionship to a full VIP experience. Whether you seek a simple relaxation or a premium sensory journey, CC's professionalism and sweet demeanor ensure an unforgettable encounter.",
      cn: "03年，身高160cm，体重45kg，胸围C+真。",
    },
    price: "$550/1h (VIP) · $450/1h · $400/30min",
    services: {
      en: [
        "Natural\u00A0bj",
        "69",
        "shower\u00A0together",
        "French\u00A0kiss",
        "stockings",
        "one\u00A0shot",
        "Extra: Cum\u00A0in\u00A0face(+$50) Cum\u00A0in\u00A0mouth&eat(+$100) second\u00A0shot(+$100)",
      ],
      cn: [
        "无套口",
        "舔蛋",
        "抚摸蛋",
        "指划蛋",
        "舔乳头",
        "情趣制服",
        "黑丝",
        "共浴",
        "69",
        "舌吻",
        "做1次",
        "VIP: 鸳鸯浴 舌吻 Kiss 360度无套口 抚摸 皖式服务 胸推 按摩 弹指 全身漫游 深喉 指滑毒龙 海底捞月 情趣内衣 丝袜 丝袜足交",
        "额外：口爆吞精(+$100) 颜射(+$50) 情景角色扮演/SM(+$150) 加一次(+$100)",
      ],
    },
    gallery: [
      "/images/girls/cc/2.webp",
      "/images/girls/cc/3.webp",
      "/images/girls/cc/4.webp",
      "/images/girls/cc/5.webp",
    ],},
  {id: 40,
    name: { en: "Fangfang", cn: "芳芳" },
    status: "available",
    verified: true,
    location: "Central",
    stats: {
      age: 24,
      height: "163cm",
      weight: "47kg",
      cup: "C (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/fangfang/1.webp",
    description: {
      en: "Gentle, sweet, and highly cooperative, the beautiful 24-year-old Fangfang is now available in Central Auckland. Standing at 163cm with a perfectly balanced figure (163cm, 47kg) and a natural C-cup, she specializes in providing a deeply relaxing sensual massage and an unforgettable VIP experience. Her warm smile and attentive touch are designed to melt all of your worries away and guide you into a state of absolute relaxation.",
      cn: "温柔娇美、极具配合度的24岁女孩芳芳，现已来到中区为您提供舒缓身心的温馨陪伴。她拥有163cm、47kg的匀称娇躯，天然C罩杯性感曲线与白嫩肌肤。专业定制SVIP与全套互动体验，包含双人淋浴、缠绵舌吻、性感黑丝、胸推漫游、深度无套口及口爆等项目。她将以最温暖的笑容与体贴入微的抚触，为您拂去所有疲惫，尽享私密欢愉。",
    },
    price: "$320 / 1h (VIP) · $240 / 1h · $200 / 30min",
    services: {
      en: [
        "French kiss",
        "Shower together",
        "Sensory massage",
        "69",
        "Body slide",
        "Natural BJ",
        "Multi shots",
        "VIP: Natural BJ · French kiss · 69 · Cum in mouth · Multi shots · Shower together · Body slide",
      ],
      cn: [
        "舌吻",
        "双人洗浴",
        "感官按摩",
        "69",
        "胸推漫游",
        "无套口",
        "多次数",
        "VIP套餐：无套口 · 舌吻 · 69 · 口爆 · 多次数 · 双人洗浴 · 胸推漫游",
      ],
    },
    gallery: [
      "/images/girls/fangfang/2.webp",
      "/images/girls/fangfang/3.webp",
      "/images/girls/fangfang/data1.webp",
      "/images/girls/fangfang/data2.webp",
    ],},
  {id: 38,
    name: { en: "Elsa", cn: "Elsa" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 26,
      height: "165cm",
      weight: "47kg",
      cup: "B+",
      nationality: "Chinese",
    },
    image: "/images/girls/elsa/1.webp",
    description: {
      en: "Elsa is a gentle and charming lady with a slender waist and beautiful curves. Known for her flexibility and ability to master various positions, she provides a high-quality, intimate experience. Whether you're looking for a relaxing massage or an adventurous encounter, Elsa's versatility and warm personality will ensure a memorable time.",
      cn: "柔软柳叶腰，大圆翘臀，温柔可人，\n各种姿势拿捏🤏🏻",
    },
    price: "$300 / 1h · $380 / VIP全包",
    services: {
      en: [
        "Bj",
        "shower\u00A0together",
        "Love's\u00A0prattle",
        "licking\u00A0eggs",
        "Flirting",
        "Massage",
        "Love\u00A0once",
        "Extra:\u00A0natural\u00A0bj\u00A0(+$20)",
        "Extra:\u00A0CIM\u00A0(+$50)",
        "VIP:\u00A0All\u00A0Inclusive",
      ],
      cn: [
        "带套口",
        "鸳鸯浴",
        "唇吻",
        "舔蛋蛋",
        "调情",
        "按摩",
        "做1次",
        "额外：无套口(+$20)",
        "额外：口报(+$50)",
        "VIP：全包所有服务和额外",
      ],
    },
    gallery: [
      "/images/girls/elsa/2.webp",
      "/images/girls/elsa/data1.webp",
      "/images/girls/elsa/data2.webp",
    ],
    video: "/images/girls/elsa/video.mp4",},
  {id: 34,
    name: { en: "Bingbing", cn: "冰冰" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 25,
      height: "168cm",
      weight: "45kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/bingbing_sister/2.webp",
    video: "/images/girls/bingbing_sister/video.mp4",
    description: {
      en: "Newly arrived from China, Bingbing is one half of our stunning 'Sister Duo'. With her sophisticated 'mature sister' (Yujie) elegance and beautiful presence, she offers a professional and highly engaging experience. Her perfectly curved figure and private specialized techniques ensure an unforgettable encounter.",
      cn: "🆕国内空降🪂姐妹花之冰冰，刚落地✈️\n🛬御姐气质风 漂亮🤩纯纯御姐风 \n冰冰前凸后翘有私密绝活哦",
    },
    price: "$400 / 1h · $350 / 45min · $300 / 30min",
    services: {
      en: [
        "Natural\u00A0bj",
        "shower\u00A0together",
        "kiss",
        "stockings",
        "breast\u00A0massage",
        "love\u00A0once",
        "Extra: Rimming(+$50) cim\u00A0in\u00A0mouth(+$50) second\u00A0time(+$50)",
      ],
      cn: [
        "无套口",
        "陪浴",
        "浅吻",
        "黑丝",
        "指滑",
        "水中捞月",
        "胸推",
        "全身漫游",
        "做1次",
        "额外：第二次(+$50) 口报(+$50) 毒龙(+$50)",
      ],
    },
    gallery: [
      "/images/girls/bingbing_sister/1.webp",
      "/images/girls/bingbing_sister/3.webp",
      "/images/girls/bingbing_sister/4.webp",
      "/images/girls/bingbing_sister/5.webp",
      "/images/girls/bingbing_sister/data1.webp",
      "/images/girls/bingbing_sister/data2.webp",
    ],},
  {id: 35,
    name: { en: "Shanshan", cn: "珊珊" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 25,
      height: "166cm",
      weight: "45kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/shanshan_sister/1.webp",
    description: {
      en: "Newly arrived from China, Shanshan is the second half of our elite 'Sister Duo'. She brings a refined 'mature sister' (Yujie) charm and a slender, delicate physique. Known for her fair, tender skin and graceful presence, she provides a high-quality service that is both refreshing and deeply satisfying.",
      cn: "🆕国内空降🪂姐妹花之珊珊，刚落地✈️\n🛬御姐气质风 漂亮🤩纯纯御姐风 \n姗姗身材细巧苗条身材 皮肤白嫩 🎉🎉🎉",
    },
    price: "$400 / 1h · $350 / 45min · $300 / 30min",
    services: {
      en: [
        "Natural\u00A0bj",
        "69",
        "shower\u00A0together",
        "kiss",
        "stockings",
        "breast\u00A0massage",
        "love\u00A0once",
        "Extra: Rimming(+$50) cim\u00A0in\u00A0mouth(+$50) second\u00A0time(+$50)",
      ],
      cn: [
        "无套口",
        "69",
        "陪浴",
        "浅吻",
        "黑丝",
        "指滑",
        "水中捞月",
        "胸推",
        "全身漫游",
        "做1次",
        "额外：第二次(+$50) 口报(+$50) 毒龙(+$50)",
      ],
    },
    gallery: [
      "/images/girls/shanshan_sister/1.webp",
      "/images/girls/shanshan_sister/2.webp",
      "/images/girls/shanshan_sister/3.webp",
      "/images/girls/shanshan_sister/4.webp",
      "/images/girls/shanshan_sister/5.webp",
      "/images/girls/shanshan_sister/6.webp",
      "/images/girls/shanshan_sister/data1.webp",
      "/images/girls/shanshan_sister/data2.webp",
    ],},
  {id: 36,
    name: { en: "Yomi", cn: "Yomi" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 23,
      height: "162cm",
      weight: "45kg",
      cup: "B+",
      nationality: "Chinese",
    },
    image: "/images/girls/yomi/1.webp",
    description: {
      en: "Sweet and charming, Yomi is a beautiful 23-year-old with a natural B+ cup and a wonderful figure. She provides attentive and deeply satisfying service, ensuring a memorable and highly interactive experience.",
      cn: "柔软柳叶腰，大圆翘臀，温柔可人，各种姿势拿捏。拥有高颜值和魔鬼身材，性格温柔甜美，配合度极高，为您带来一场难忘的感官盛宴。",
    },
    price: "$300 / 1h",
    services: {
      en: [
        "Bj",
        "shower\u00A0together",
        "breast\u00A0massage",
        "Love's\u00A0prattle",
        "baby\u00A0slide",
        "stockings",
        "Love\u00A0once",
        "Extra:\u00A069\u00A0(+$20),\u00A0natural\u00A0bj\u00A0(+$20),\u00A0French\u00A0kiss\u00A0(+$20),\u00A0CIM\u00A0(+$50)",
        "VIP\u00A0($380):\u00A0All\u00A0inclusive\u00A0(2\u00A0shots,\u00A069,\u00A0natural\u00A0bj,\u00A0CIM,\u00A0etc)",
      ],
      cn: [
        "带套口",
        "鸳鸯浴",
        "唇吻",
        "胸推",
        "甜🥚🥚",
        "调情",
        "做1次",
        "额外：无套口(+$20), 蛇吻(+$20), 69(+$20), 口爆(+$50)",
        "VIP($380)：全包所有服务和额外(包含做2次等)",
      ],
    },
    gallery: [
      "/images/girls/yomi/1.webp",
      "/images/girls/yomi/2.webp",
      "/images/girls/yomi/3.webp",
      "/images/girls/yomi/4.webp",
      "/images/girls/yomi/5.webp",
      "/images/girls/yomi/6.webp",
      "/images/girls/yomi/7.webp",
      "/images/girls/yomi/8.webp",
      "/images/girls/yomi/data1.webp",
      "/images/girls/yomi/data2.webp",
    ],},
  {id: 3,
    name: { en: "Momo", cn: "Momo" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 25,
      height: "171cm",
      weight: "50kg",
      cup: "D",
      nationality: "Chinese",
    },
    image: "/images/girls/momo/1.webp",
    description: {
      en: "A professional and trained talent newly arrived from China. Momo offers a unique and high-end sensory experience with expert performance skills and a captivating presence.",
      cn: "国内空降刚落地🪂，AV女优专业训练的莞式服务，可S（专业艳舞表演 可免费观看）按摩养生不在话下，让你体验一场不一样的愉悦的快感，你会是那位男主角吗？请务必来体验哦，快来找我吧……😘😘",
    },
    price: "$400 / 1h · $350 / 30min",
    services: {
      en: [
        "Natural\u00A0bj",
        "69",
        "shower\u00A0together",
        "French\u00A0kiss",
        "stockings",
        "breast\u00A0massage",
        "love\u00A0once",
        "Extra: Cim\u00A0in\u00A0mouth(+$50) Rimming(+$50) second\u00A0time(+$50)",
      ],
      cn: [
        "无套口",
        "69",
        "陪浴",
        "舌吻",
        "黑丝",
        "艳舞表演",
        "前列腺高潮",
        "全身漫游",
        "额外：第二次(+$50) 口爆(+$50) 毒龙(+$50)",
      ],
    },
    gallery: [
      "/images/girls/momo/1.webp",
      "/images/girls/momo/2.webp",
      "/images/girls/momo/3.webp",
      "/images/girls/momo/4.webp",
      "/images/girls/momo/5.webp",
      "/images/girls/momo/6.webp",
      "/images/girls/momo/7.webp",
      "/images/girls/momo/8.webp",
      "/images/girls/momo/9.webp",
      "/images/girls/momo/10.webp",
      "/images/girls/momo/11.webp",
      "/images/girls/momo/12.webp",
      "/images/girls/momo/13.webp",
      "/images/girls/momo/14.webp",
    ],},
  {id: 4,
    name: { en: "Lamb", cn: "小绵羊" },
    status: "hidden",
    verified: true,
    location: "Central",
    stats: {
      age: 22,
      height: "169cm",
      weight: "44kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/lamb/4.webp",
    description: {
      en: "Sweet and gentle, Lamb (Xiao Mian Yang) is the ultimate 'girl next door' beauty now based in Auckland CBD. With her soft, delicate voice and incredibly smooth skin, she offers an intimate experience that feels genuinely warm and professional. Her slender yet curvaceous 162cm frame and sweet personality ensure a high-end encounter that is both relaxed and deeply satisfying.",
      cn: "小绵羊🐑😘温柔体贴甜甜可爱 纯纯小良家 声音嗲嗲的 刚下海不久 完美身材前凸后翘 皮肤光滑白嫩白嫩",
    },
    price: "$650 / 90min · $450 / 1h",
    services: {
      en: [
        "Natural\u00A0bj",
        "shower\u00A0together",
        "French\u00A0kiss",
        "stockings",
        "breast\u00A0massage",
        "69",
        "second\u00A0time",
        "One\u00A0shot\u00A0only\u00A0in\u00A060\u00A0minutes",
      ],
      cn: [
        "无套口",
        "陪浴",
        "69",
        "蛇吻",
        "黑丝",
        "按摩",
        "做2次",
        "60分钟只做一次",
      ],
    },
    gallery: [
      "/images/girls/lamb/4.webp",
      "/images/girls/lamb/1.webp",
      "/images/girls/lamb/2.webp",
      "/images/girls/lamb/3.webp",
      "/images/girls/lamb/5.webp",
      "/images/girls/lamb/6.webp",
    ],},
  {id: 5,
    name: { en: "Youyou", cn: "优优" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 26,
      height: "163cm",
      weight: "47kg",
      cup: "C",
      nationality: "china",
    },
    image: "/images/girls/youyou/1.webp",
    description: {
      en: "A gentle and elegant beauty with a sophisticated presence. Youyou is known for her sweet, obedient nature and exceptional high level of cooperation. She offers both relaxing massage therapy and deeply intimate full sessions with a focus on providing a warm, caring experience.",
      cn: "良家初下海，温柔乖巧，懂事听话，气质小姐姐，服务系，配合度高，可半套。",
    },
    price: "$340 / 1h · $300 / 45min · $260 / 30min · $160 / 1h (Half)",
    services: {
      en: [
        "Natural\u00A0bj",
        "shower\u00A0together",
        "French\u00A0kiss",
        "stockings",
        "breast\u00A0massage",
        "69",
        "second\u00A0time",
        "(30mins\u00A0only\u00A0ones)",
      ],
      cn: [
        "陪澡",
        "69",
        "无套口",
        "舌吻",
        "黑丝",
        "按摩",
        "爱2次 (半小时1次)",
        "可半🍑 ($160/1h)",
      ],
    },
    gallery: [
      "/images/girls/youyou/1.webp",
      "/images/girls/youyou/2.webp",
      "/images/girls/youyou/3.webp",
      "/images/girls/youyou/4.webp",
      "/images/girls/youyou/5.webp",
      "/images/girls/youyou/6.webp",
      "/images/girls/youyou/7.webp",
      "/images/girls/youyou/8.webp",
    ],},
  {id: 7,
    name: { en: "Laila", cn: "莱拉" },
    status: "available",
    verified: true,
    isOnHomepage: false,
    location: "CBD",
    stats: {
      age: 25,
      height: "168cm",
      weight: "60kg",
      cup: "F",
      nationality: "Chinese",
    },
    image: "/images/girls/laila/2.webp",
    video: "/images/girls/laila/video.mp4",
    description: {
      en: "Elegant and passionate, Laila is a stunning Chinese beauty with a natural F cup figure. Her gentle touch, professional massage, and commitment to delivering a truly immersive and pleasurable experience make her an unforgettable companion for those seeking a premium escape.",
      cn: "典雅而充满激情，莱拉是一位拥有天然F杯傲人身材的中国美女。她温柔的触碰、典雅的气质以及为您提供完全沉浸且愉悦体验的承诺，使她成为奥克兰高端私密服务的难忘选择。",
    },
    price: "$320 / 1h (VIP) · $240 / 1h",
    services: {
      en: [
        "shower\u00A0together",
        "Bj",
        "breast\u00A0Massage",
        "French\u00A0kiss",
        "baby\u00A0slide",
        "stockings",
        "Love\u00A0once",
        "Extra: natural\u00A0bj(+$30) toy(+$50) Com\u00A0in\u00A0mouth(+$30)",
      ],
      cn: [
        "调情",
        "舌吻",
        "戴套吹",
        "鸳鸯浴",
        "水中箫",
        "制服诱惑",
        "简单按摩",
        "激情性爱",
        "做一次",
        "额外：无套口(+$30) 口爆(+$30) 玩具(+$50)",
      ],
    },
    gallery: [
      "/images/girls/laila/2.webp",
      "/images/girls/laila/3.webp",
      "/images/girls/laila/4.webp",
      "/images/girls/laila/5.webp",
      "/images/girls/laila/6.webp",
      "/images/girls/laila/7.webp",
      "/images/girls/laila/8.webp",
      "/images/girls/laila/9.webp",
      "/images/girls/laila/1.webp",
    ],},
  {id: 8,
    name: { en: "Barbara", cn: "芭芭拉" },
    status: "unavailable",
    verified: true,
    location: "CBD",
    stats: {
      age: 24,
      height: "163cm",
      weight: "48kg",
      cup: "C",
      nationality: "Vietnamese",
    },
    image: "/images/girls/barbara/1.webp",
    description: {
      en: "Exotic and charming, Barbara is a 24-year-old Vietnamese beauty. With her slender figure and radiant personality, she offers a wide variety of services including professional massage and intimate companionship to ensure a deeply relaxing and pleasurable experience.",
      cn: "充满异域风情且迷人，芭芭拉是一位24岁的越南美女。她拥有苗条的身材和开朗的性格，提供包括专业按摩和亲密陪伴在内的多种服务，致力于为您带来深度放松和愉悦的体验。",
    },
    price: "$320 / 1h (VIP) · $260 / 1h · $200 / 30min",
    services: {
      en: [
        "69",
        "shower\u00A0together",
        "French\u00A0kiss",
        "stockings",
        "breast\u00A0massage",
        "Do\u00A0it\u00A0once",
        "Extra: natural\u00A0bj(+$20) natural\u00A0bj&cim\u00A0in\u00A0mouth(+$50) second\u00A0time(+$40)",
      ],
      cn: [
        "陪浴",
        "69",
        "舌吻",
        "黑丝",
        "按摩",
        "做1次",
        "额外：第二次(+$40) 无套口(+$20) 无套口&口报(+$50)",
      ],
    },
    gallery: [
      "/images/girls/barbara/1.webp",
      "/images/girls/barbara/2.webp",
      "/images/girls/barbara/3.webp",
      "/images/girls/barbara/4.webp",
      "/images/girls/barbara/5.webp",
      "/images/girls/barbara/6.webp",
      "/images/girls/barbara/7.webp",
    ],},
  {id: 9,
    name: { en: "Anan", cn: "安安" },
    status: "leave",
    verified: true,
    location: "CBD",
    stats: {
      age: 26,
      height: "166cm",
      weight: "48kg",
      cup: "36C",
      nationality: "Chinese",
    },
    image: "/images/girls/anan/1.webp",
    video: "/videos/anan.mov",
    description: {
      en: "A professional and attentive experience tailored to your needs. Anan is highly skilled in various relaxation techniques and ensures a comfortable, high-quality session.",
      cn: "专业细致，配合度高，为您提供高品质、定制化的放松体验。",
    },
    price: "$350 / 1h (VIP) · $240 / 1h · $200 / 30min · $160 / 1h (Half)",
    services: {
      en: [
        "shower\u00A0together",
        "Bj",
        "breast\u00A0Massage",
        "baby\u00A0slide",
        "stockings",
        "second\u00A0time",
        "Extra: 69(+$30) natural\u00A0bj(+$20) French\u00A0kiss(+$30) com\u00A0in\u00A0mouth(+$50) rimming(+$50)",
      ],
      cn: [
        "洗澡",
        "胸推",
        "按摩",
        "戴套口",
        "情趣内衣",
        "有2次",
        "VIP: 莞式一条龙，服务全包",
        "额外：无套口(+$20) 口爆(+$50) 69(+$30) 舌吻(+$30) 毒龙(+$50)",
      ],
    },
    gallery: [
      "/images/girls/anan/1.webp",
      "/images/girls/anan/2.webp",
      "/images/girls/anan/5.webp",
      "/images/girls/anan/6.webp",
      "/images/girls/anan/7.webp",
      "/images/girls/anan/8.webp",
      "/images/girls/anan/9.webp",
      "/images/girls/anan/10.webp",
      "/images/girls/anan/11.webp",
      "/images/girls/anan/12.webp",
    ],},
  {id: 10,
    name: { en: "Kaka", cn: "卡卡" },
    status: "available",
    verified: true,
    location: "CBD",
    stats: {
      age: 26,
      height: "168cm",
      weight: "47kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/kaka/1.webp",
    description: {
      en: "A charming and attentive professional dedicated to providing a high-quality, personalized service. With her graceful figure and warm personality, Kaka specializes in traditional massage combined with intimate sensory care. She is highly cooperative and ensures every session is tailored to your specific preferences for an unforgettable experience.",
      cn: "温柔体贴，服务态度好，配合度高。擅长专业按摩与深度感官服务，致力于为您打造尊贵舒适的私享体验。",
    },
    price: "$160 / 1h (Half)",
    services: {
      en: [
        "Sensual\u00A0massage",
        "Extra: Take\u00A0it\u00A0off\u00A0completely(+$30) natural\u00A0bj(+$30)",
      ],
      cn: [
        "按摩",
        "带套口",
        "飞机",
        "额外：脱上衣(+$20) 全裸(+$30) 无套口(+$30)",
      ],
    },
    gallery: [
      "/images/girls/kaka/1.webp",
      "/images/girls/kaka/2.webp",
      "/images/girls/kaka/3.webp",
      "/images/girls/kaka/4.webp",
    ],},
  {id: 11,
    name: { en: "Puffy", cn: "泡芙" },
    status: "available",
    verified: true,
    location: "CBD",
    stats: {
      age: 26,
      height: "168cm",
      weight: "47kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/paofu/1.webp",
    description: {
      en: "Elegant and sophisticated, Puffy is a warm and dedicated professional who provides a personalized, intoxicated experience.",
      cn: "气质型，温柔贴心，醉情人。",
    },
    price: "$300 / 1h · $240 / 30min",
    services: {
      en: [
        "shower\u00A0together",
        "Bj",
        "Love's\u00A0prattle",
        "Massage",
        "Lingerie",
        "baby\u00A0slide",
        "stockings",
        "Love\u00A0once",
        "Extra: natural\u00A0Bj(+$50)",
      ],
      cn: ["鸳鸯浴", "带套口", "爱爱一次", "额外：无套口(+$50)"],
    },
    gallery: [
      "/images/girls/paofu/1.webp",
      "/images/girls/paofu/2.webp",
      "/images/girls/paofu/3.webp",
      "/images/girls/paofu/4.webp",
    ],},
  {id: 12,
    name: { en: "Linda", cn: "琳达" },
    status: "available",
    verified: true,
    location: "CBD",
    stats: {
      age: 23,
      height: "166cm",
      weight: "55kg",
      cup: "36C",
      nationality: "Chinese",
    },
    image: "/images/girls/linda/1.webp",
    description: {
      en: "A versatile and passionate professional, Linda offers a high-end experience with a wide range of specialized services to ensure your total satisfaction.",
      cn: "多才多艺且充满热情，琳达提供高品质、全方位的专业服务，致力于让您的每一次体验都无懈可击。",
    },
    price: "$300 / 1h (VIP) · $220 / 1h · $170 / 30min",
    services: {
      en: [
        "Water roaming",
        "Sensual climb",
        "Shower together",
        "Extra: Natural BJ (+$20)",
        "VIP: Oral finish · Bedside Cantonese service · Russian style · Cowgirl · Side parking · Rimming · Full-body roaming · Lingering sweetness",
      ],
      cn: [
        "水中漫游",
        "猛虎上山",
        "鸳鸯戏水",
        "额外: 无套口 (+$20)",
        "VIP套餐：口爆 · 床头广式服务 · 俄罗斯大战 · 观音坐莲 · 侧方式停车 · 毒龙 · 全身漫游 · 回味无穷",
      ],
    },
    gallery: [
      "/images/girls/linda/1.webp",
      "/images/girls/linda/2.webp",
      "/images/girls/linda/3.webp",
      "/images/girls/linda/4.webp",
      "/images/girls/linda/5.webp",
      "/images/girls/linda/6.webp",
      "/images/girls/linda/7.webp",
      "/images/girls/linda/data1.webp",
      "/images/girls/linda/data2.webp",
    ],},
  {id: 13,
    name: { en: "Faye", cn: "语橙" },
    status: "leave",
    verified: true,
    location: "Central",
    stats: {
      age: 19,
      height: "170cm",
      weight: "45kg",
      cup: "E",
      nationality: "Thailand",
    },
    image: "/images/girls/faye/1.webp",
    description: {
      en: "Pure and radiant, Faye (语橙) is a 19-year-old international student from Thailand. With her tall, slender figure and healthy sun-kissed skin, she offers a genuine and refreshing experience. Specializing in Thai massage and intimate companionship, she ensures a deeply relaxing time with a focus on quality and discretion.",
      cn: "泰国🇹🇭 Faye，中文名：语橙。真正的留学生，19岁（真实2006年护照为证），颜值不错，身材高挑，健康肤色，清纯系女生。",
    },
    price: "$340 / 1h · $260 / 30min · $160 / 1h (Half)",
    services: {
      en: [
        "bj",
        "shower\u00A0together",
        "French\u00A0kiss",
        "stockings",
        "breast\u00A0massage",
        "69",
        "second\u00A0time (No second time in 30mins)",
        "Note: It\u00A0cannot\u00A0be\u00A0natural\u00A0bj\u00A0and\u00A0not\u00A0French\u00A0kissing",
      ],
      cn: [
        "陪浴",
        "带套口",
        "全身漫游",
        "69",
        "浅吻",
        "指划",
        "丝袜",
        "泰式按摩",
        "第二次 (约半小时的只能做一次)",
      ],
    },
    gallery: [
      "/images/girls/faye/1.webp",
      "/images/girls/faye/2.webp",
      "/images/girls/faye/3.webp",
      "/images/girls/faye/4.webp",
      "/images/girls/faye/5.webp",
      "/images/girls/faye/6.webp",
    ],},
  {id: 14,
    name: { en: "Yuxi", cn: "羽西" },
    status: "available",
    verified: true,
    location: "CBD",
    stats: {
      age: 28,
      height: "170cm",
      weight: "55kg",
      cup: "D",
      nationality: "Chinese",
    },
    image: "/images/girls/yuxi/1.webp",
    description: {
      en: "Elegant and versatile, Yuxi is a tall (170cm) and stunning beauty with a refined D-cup figure. She offers a unique range of services in Central Auckland, specializing in both full sensory experiences and professional therapeutic bodywork. From romantic 'S-kiss' techniques to specialized prostate maintenance, her sessions are thorough and deeply relaxing. Her VIP package includes multiple rounds and an even more extensive service menu for the ultimate indulgence.",
      cn: "优雅大气、高挑迷人，羽西身高 170cm，拥有出众的 D 杯身材。她不仅擅长细腻缠绵的感官互动，如共浴、舌吻和漫游，更有专业的按摩以及专为男士打造的前列腺保养服务。无论是追求浪漫互动还是深度舒缓，她都能为您提供超预期的完美体验。她的 $320 VIP 套餐更包含制服诱惑、多次陪伴及无套深度陪伴，让您尽享丝滑奢宠。",
    },
    price: "$320 / 1h (VIP) · $240 / 1h · $200 / 30min · $160 / 1h (Half)",
    services: {
      en: [
        "Flirting",
        "BJ (condom)",
        "Shower BJ",
        "Deep kiss",
        "Bath together",
        "Body slide",
        "69",
        "2 shots",
        "Extra: Natural BJ (+$20)",
        "VIP: Flirting · Deep kiss · Natural BJ · Bath together · Uniform · Stockings · Professional Massage · Sex · Breast massage · Butt massage · Body slide · Water slide · Deep throat · Shower BJ · Rimming · Come in mouth · 2 shots",
      ],
      cn: [
        "调情",
        "戴套口",
        "水中萧",
        "舌吻",
        "共浴",
        "漫游",
        "69",
        "可2次",
        "额外: 无套口 (+$20)",
        "VIP套餐：无套吹 · 调情 · 舌吻 · 共浴 · 制服 · 黑丝 · 专业按摩 · 爱爱 · 胸推 · 臀推 · 漫游 · 过水 · 口痧 · 水中萧 · 毒龙 · 口爆 · 可2次",
      ],
    },
    gallery: [
      "/images/girls/yuxi/1.webp",
      "/images/girls/yuxi/2.webp",
      "/images/girls/yuxi/3.webp",
      "/images/girls/yuxi/4.webp",
      "/images/girls/yuxi/5.webp",
      "/images/girls/yuxi/6.webp",
      "/images/girls/yuxi/7.webp",
      "/images/girls/yuxi/8.webp",
      "/images/girls/yuxi/data1.webp",
      "/images/girls/yuxi/data2.webp",
    ],},
  {id: 15,
    name: { en: "Sisi", cn: "思思" },
    status: "available",
    verified: true,
    location: "East",
    stats: {
      age: 26,
      height: "165cm",
      weight: "47kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/sisi/1.webp",
    description: {
      en: "Radiant and charming, Sisi (Si Si) offers a premium sensory experience in East Auckland. Standing at 165cm with a graceful figure, she excels in delivering deep relaxation through specialized sensory massage. Her VIP tier is exceptionally comprehensive, featuring a luxury bath together, body slides, and multiple intimate rounds for a truly indulgent escape.",
      cn: "明亮动人、极具魅力，思思为您在东区带来一场至臻感官盛宴。她身高 165cm，身材曼妙，擅长通过专业的感官按摩为您带来深度放松。她的 VIP 套餐配置豪华，包含一起洗澡、胸推漫游以及无套口等深度服务，并支持多次陪伴，让您尽享私密尊贵的悠闲时光。",
    },
    price: "$320 / 1h (VIP) · $250 / 30min (VIP) · $220 / 1h · $180 / 30min",
    services: {
      en: [
        "Full\u00A0service (include\u00A0sex,massage,69,bj,body\u00A0slide)",
        "Full\u00A0service (include\u00A0sex,multi\u00A0shots,natural\u00A0bj,69,body\u00A0slide,massage,shower\u00A0together,kiss)",
        "VIP: (include\u00A0all\u00A0Full\u00A0service\u00A0plus\u00A0extra\u00A0come\u00A0in\u00A0mouth)",
      ],
      cn: [
        "接吻",
        "感官按摩",
        "69",
        "戴套吹",
        "啪一次",
        "VIP: 蛇吻 陪浴 胸推漫游 感官按摩 无套口 69 口爆 多次",
      ],
    },
    gallery: [
      "/images/girls/sisi/1.webp",
      "/images/girls/sisi/2.webp",
      "/images/girls/sisi/3.webp",
      "/images/girls/sisi/4.webp",
      "/images/girls/sisi/5.webp",
      "/images/girls/sisi/6.webp",
      "/images/girls/sisi/7.webp",
      "/images/girls/sisi/8.webp",
      "/images/girls/sisi/9.webp",
      "/images/girls/sisi/10.webp",
      "/images/girls/sisi/11.webp",
      "/images/girls/sisi/12.webp",
    ],},
  {id: 16,
    name: { en: "Candice", cn: "Candice" },
    status: "available",
    verified: true,
    location: "Central",
    stats: {
      age: "26+",
      height: "160cm",
      weight: "46kg",
      cup: "B-C",
      nationality: "Chinese",
    },
    image: "/images/girls/candice/1.webp",
    description: {
      en: "Experienced and professional, Candice focuses on high-quality service and attention to detail. Specially trained in premium massage and intimate companionship, she offers a deeply relaxing experience including traditional massage and free cupping therapy.",
      cn: "经验丰富、专业典雅，Candice 专注于为您提供最高品质的服务。凭借成熟的专业手法，她通过精致的按摩和贴心的陪伴为您带来极致放松的体验。店内还为客人免费提供拔火罐等理疗选项。",
    },
    price: "$250 / 1h (VIP) · $220 / 30min (VIP) · $200 / 1h · $150 / 30min",
    services: {
      en: [
        "Full\u00A0service: 30mins/$150 (include\u00A0sex,massage,69,bj,body\u00A0slide)",
        "Full\u00A0service: 60mins/$200 (include\u00A0sex,multi\u00A0shots,natural\u00A0bj,69,body\u00A0slide,massage,shower\u00A0together,kiss)",
        "VIP: 30mins/$220 60mins/$250 (include\u00A0all\u00A0Full\u00A0service\u00A0plus\u00A0extra\u00A0come\u00A0in\u00A0mouth)",
      ],
      cn: [
        "洗澡",
        "按摩",
        "无套口",
        "接吻",
        "做2次",
        "VIP: 莞式服务",
        "免费赠送: 拔火罐",
      ],
    },
    gallery: [
      "/images/girls/candice/1.webp",
      "/images/girls/candice/2.webp",
      "/images/girls/candice/3.webp",
      "/images/girls/candice/4.webp",
      "/images/girls/candice/5.webp",
      "/images/girls/candice/6.webp",
      "/images/girls/candice/7.webp",
    ],},
  {id: 17,
    name: { en: "Cherry", cn: "Cherry" },
    status: "leave",
    verified: true,
    location: "Central",
    stats: {
      age: 26,
      height: "157cm",
      weight: "45kg",
      cup: "D",
      nationality: "Chinese",
    },
    image: "/images/girls/cherry/1.webp",
    description: {
      en: "Delicate and charming, Cherry is a professional therapist in Central Auckland. Known for her petite 157cm figure and stunning natural D cup, she offers a perfect blend of high-quality massage and warm, intimate companionship. Whether you're seeking a standard or premium VIP experience, her attentive touch will ensure absolute relaxation.",
      cn: "娇小玲珑、魅力十足，Cherry 是中区备受推崇的高端服务者。她拥有 157cm 的玲珑身材和傲人的天然 D 杯，将精湛的按摩手法与温柔的贴心陪伴完美结合。无论您是选择标准套餐还是极致的 VIP 体验，她细腻的触碰都将为您带来一场难忘的舒压之旅。",
    },
    price: "$300 / 1h (VIP) · $250 / 30分钟 (VIP) · $220 / 1h · $160 / 30分钟",
    services: {
      en: [
        "shower\u00A0together",
        "Bj",
        "breast\u00A0Massage",
        "baby\u00A0slide",
        "stockings",
        "Love\u00A0once",
        "VIP: natural\u00A0bj 69 second\u00A0time Hip\u00A0massage French\u00A0kiss",
      ],
      cn: [
        "按摩",
        "调情",
        "有套口",
        "kiss",
        "爱一次",
        "VIP: 无套口 蛇吻 69 陪浴 2-3次",
      ],
    },
    gallery: [
      "/images/girls/cherry/1.webp",
      "/images/girls/cherry/2.webp",
      "/images/girls/cherry/3.webp",
      "/images/girls/cherry/4.webp",
      "/images/girls/cherry/5.webp",
    ],},
  {id: 18,
    name: { en: "Emma", cn: "Emma" },
    status: "available",
    verified: true,
    location: "Central",
    stats: {
      age: "28+",
      height: "162cm",
      weight: "49kg",
      cup: "B",
      nationality: "Chinese",
    },
    image: "/images/girls/emma/1.webp",
    description: {
      en: "Sophisticated and experienced, Emma offers a premium relaxation experience in Central Auckland. Standing at 162cm, she combines professional massage with intimate care. Her VIP service is exceptionally comprehensive, including extended rounds and specialized intimate techniques for those seeking the ultimate escape.",
      cn: "典雅稳重、经验丰富，Emma 为您在中区提供高品质的舒压体验。她身高 162cm，将专业的按摩技巧与细腻的温情看护完美结合。她的 VIP 服务极具诚意，包含多 round 陪伴和多种特色私密技巧，是追求极致放松体验的不二之选。",
    },
    price: "$300 / 1h (VIP) · $200 / 1h · $160 / 30分钟",
    services: {
      en: [
        "Shower\u00A0together",
        "69",
        "Bj",
        "massage",
        "Love\u00A0once",
        "Extra: second\u00A0time(+$30)",
        "VIP: Natural\u00A0bj French\u00A0kiss 69 com\u00A0in\u00A0mouth rimming second\u00A0time",
      ],
      cn: [
        "洗澡",
        "带套口",
        "69",
        "kiss",
        "按摩",
        "啪1次",
        "额外: 第二次(+$30)",
        "VIP: 无套口 口爆 毒龙 第2次",
      ],
    },
    gallery: [
      "/images/girls/emma/1.webp",
      "/images/girls/emma/2.webp",
      "/images/girls/emma/3.webp",
      "/images/girls/emma/4.webp",
    ],},
  {id: 19,
    name: { en: "Jessica", cn: "Jessica" },
    status: "available",
    verified: true,
    location: "Central",
    stats: {
      age: "28+",
      height: "162cm",
      weight: "49kg",
      cup: "B",
      nationality: "Chinese",
    },
    image: "/images/girls/jessica/1.webp",
    description: {
      en: "Elegant and poised, Jessica provides a high-standard service in Central Auckland. Standing at 162cm with a slim 49kg figure, she offers a perfect balance of professional massage and warm companionship. Her extensive service list ensures every visit is tailored to your preferences, promising a deeply satisfying and relaxing experience.",
      cn: "典雅端庄、气质出众，Jessica 是中区为您提供高标准服务的理想之选。她身高 162cm，体重 49kg，身材匀称，将专业的按摩手法与温柔的贴心陪伴完美融合。她丰富的服务项目确保能满足您的各种需求，为您带来一场深度放松且极度愉悦的私密体验。",
    },
    price: "$300 / 1h (VIP) · $200 / 1h · $160 / 30min",
    services: {
      en: [
        "Shower\u00A0together",
        "69",
        "Bj",
        "massage",
        "Love\u00A0once",
        "Extra: second\u00A0time(+$30)",
        "VIP: Natural\u00A0bj French\u00A0kiss 69 com\u00A0in\u00A0mouth rimming second\u00A0time",
      ],
      cn: ["洗澡", "带套口", "69", "吻", "按摩", "啪1次", "第二次: +$30"],
    },
    gallery: [
      "/images/girls/jessica/1.webp",
      "/images/girls/jessica/2.webp",
      "/images/girls/jessica/3.webp",
      "/images/girls/jessica/4.webp",
      "/images/girls/jessica/5.webp",
    ],},
  {id: 20,
    name: { en: "Ying", cn: "小英" },
    status: "hidden",
    verified: true,
    location: "Central",
    stats: {
      age: "26+",
      height: "160cm",
      weight: "43kg",
      cup: "B-C",
      nationality: "Chinese",
    },
    image: "/images/girls/ying/1.webp",
    description: {
      en: "Petite and energetic, Ying (Xiao Ying) offers a comprehensive 'Dongguan style' service in Central Auckland. At 160cm, she pairs her professional massage skills with a high degree of intimacy and attentiveness. Her VIP package is exceptionally detailed, even including a complimentary cupping treatment for a full wellness experience. She is known for her warm personality and commitment to total relaxation.",
      cn: "身材娇小、活力十足，小英为您在中区提供极具特色的“莞式服务”。她身高 160cm，将专业的按摩技巧与细腻的温情看护完美结合，服务态度极佳。她的 VIP 套餐诚意满满，包含全方位的深度放松，并特别赠送拔火罐调理。她以亲切的个性和极高的配合度著称，致力于为您打造一场全身心放松的至臻体验。",
    },
    price: "$250 / 1h (VIP) · $220 / 30min (VIP) · $180 / 1h · $130 / 30min",
    services: {
      en: [
        "Full\u00A0service: 30mins/$130 (include\u00A0sex,massage,69,bj,body\u00A0slide)",
        "Full\u00A0service: 60mins/$180 (include\u00A0sex,multi\u00A0shots,natural\u00A0bj,69,body\u00A0slide,massage,shower\u00A0together,kiss)",
        "VIP: 30mins/$220 60mins/$250 (include\u00A0all\u00A0Full\u00A0service\u00A0plus\u00A0extra\u00A0come\u00A0in\u00A0mouth)",
      ],
      cn: [
        "洗澡",
        "按摩",
        "无套口",
        "接吻",
        "做2次",
        "VIP: 莞式服务",
        "免费赠送: 拔火罐",
      ],
    },
    gallery: [
      "/images/girls/ying/1.webp",
      "/images/girls/ying/2.webp",
      "/images/girls/ying/3.webp",
      "/images/girls/ying/4.webp",
      "/images/girls/ying/5.webp",
      "/images/girls/ying/6.webp",
      "/images/girls/ying/7.webp",
      "/images/girls/ying/8.webp",
      "/images/girls/ying/9.webp",
      "/images/girls/ying/10.webp",
    ],},
  {id: 21,
    name: { en: "Yang", cn: "洋洋" },
    status: "available",
    verified: true,
    location: "Central",
    stats: {
      age: "27+",
      height: "160cm",
      weight: "48kg",
      cup: "B-C",
      nationality: "Chinese",
    },
    image: "/images/girls/yang/1.webp",
    description: {
      en: "Yang (Yang Yang) is a delightful and attentive beauty providing top-tier service in Central Auckland. Standing at 160cm, she is known for her high-end 'Dongguan style' service and professional touch. Her VIP package is highly recommended, featuring a detailed wellness experience with a complimentary cupping therapy. She ensures a very high standard of satisfaction and total relaxation.",
      cn: "洋洋是中区一位笑容亲切、极具热情的资深女孩。她身高 160cm，主打高端“莞式服务”，以细腻入微的操作和极高的配合度深受好评。她的 VIP 套餐配置齐全，不仅包含全方位的贴心陪伴，还特别赠送拔火罐调理。她致力于为您打造一场全身心放松、极具沉浸感的至臻享受。",
    },
    price: "$250 / 1h (VIP) · $220 / 30min (VIP) · $180 / 1h · $130 / 30min",
    services: {
      en: [
        "Full\u00A0service (include\u00A0sex,massage,69,bj,body\u00A0slide)",
        "Full\u00A0service (include\u00A0sex,multi\u00A0shots,natural\u00A0bj,69,body\u00A0slide,massage,shower\u00A0together,kiss)",
        "VIP: (include\u00A0all\u00A0Full\u00A0service\u00A0plus\u00A0extra\u00A0come\u00A0in\u00A0mouth)",
      ],
      cn: [
        "洗澡",
        "按摩",
        "无套口",
        "接吻",
        "做2次",
        "VIP: 莞式服务",
        "免费赠送: 拔火罐",
      ],
    },
    gallery: [
      "/images/girls/yang/1.webp",
      "/images/girls/yang/2.webp",
      "/images/girls/yang/3.webp",
      "/images/girls/yang/4.webp",
    ],},
  {id: 22,
    name: { en: "Aimi", cn: "爱米" },
    status: "leave",
    verified: true,
    location: "Central",
    stats: {
      age: 26,
      height: "162cm",
      weight: "47kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/aimi/2.webp",
    description: {
      en: "Sweet and youthful, Aimi (Ai Mi) is a charming 2000-born beauty in Central Auckland. Standing at 162cm with a perfect C-cup figure, she offers an intimate experience focused on deep sensory relaxation. Her VIP service is exceptionally thorough, featuring a luxury bath together, romantic 'S-kiss' techniques, and multiple rounds. She is known for her warm energy and dedication to making every moment special.",
      cn: "温婉可人、青春洋溢，爱米是一位来自 00 后的心动女生。她身高 162cm，拥有完美的 C 杯身材，擅长通过细腻的感官按摩为您带来全方位的舒缓体验。她的 VIP 服务极其贴心周到，包含共同沐浴、缠绵蛇吻以及多次深度陪伴，让您在温馨惬意的氛围中尽享私密时光。",
    },
    price: "$320 / 1h (VIP) · $250 / 30min (VIP) · $220 / 1h · $180 / 30min",
    services: {
      en: [
        "Full\u00A0service (include\u00A0sex,massage,69,bj,body\u00A0slide)",
        "Full\u00A0service (include\u00A0sex,multi\u00A0shots,natural\u00A0bj,69,body\u00A0slide,massage,shower\u00A0together,kiss)",
        "VIP: (include\u00A0all\u00A0Full\u00A0service\u00A0plus\u00A0extra\u00A0come\u00A0in\u00A0mouth)",
      ],
      cn: [
        "接吻",
        "感官按摩",
        "69",
        "戴套口",
        "做1次",
        "VIP: 蛇吻 一起洗澡 胸推漫游 感光按摩 无套口 口爆 多次",
      ],
    },
    gallery: [
      "/images/girls/aimi/2.webp",
      "/images/girls/aimi/1.webp",
      "/images/girls/aimi/3.webp",
      "/images/girls/aimi/4.webp",
      "/images/girls/aimi/5.webp",
      "/images/girls/aimi/6.webp",
      "/images/girls/aimi/7.webp",
    ],},
  {id: 23,
    name: { en: "Blind Box", cn: "开盲盒" },
    status: "unavailable",
    verified: true,
    location: "CBD",
    stats: {
      height: "Varies",
      weight: "Varies",
      cup: "Varies",
      nationality: "Chinese",
    },
    image: "/images/girls/blindbox/grid.webp",
    description: {
      en: "Experience the thrill of the unknown with our 'Blind Box' special. For a flat rate of $360, you'll be paired with one of our high-quality surprise beauties in CBD Auckland. This discounted package includes a full sensory session with a bath, romantic techniques, and a guaranteed second round. It's the perfect way to discover a new favorite at an exceptional value.",
      cn: "开启您的心跳私密盲盒！仅需 $360 特惠价，您将随机选择一位我们在市区的高端宝藏女孩。盲盒包不仅包含温馨沐浴、缠绵蛇吻以及深度无套陪伴，更承诺两次云雨体验。在未知的惊喜中，以超值的价格选择您的下一位挚爱，尽享私密慢生活。",
    },
    price: "$360 / Special Package (2 rounds)",
    services: {
      en: [
        "Bath\u00A0together",
        "S-kiss",
        "Natural\u00A0BJ",
        "69",
        "Stockings",
        "2\u00A0rounds",
      ],
      cn: ["陪浴", "蛇吻", "无套口", "69", "丝袜", "满2次"],
    },
    gallery: [
      "/images/girls/blindbox/grid.webp",
      "/images/girls/blindbox/1.webp",
      "/images/girls/blindbox/2.webp",
      "/images/girls/blindbox/3.webp",
      "/images/girls/blindbox/4.webp",
      "/images/girls/blindbox/5.webp",
      "/images/girls/blindbox/6.webp",
    ],},
  {id: 24,
    name: { en: "Yumo", cn: "语沫" },
    status: "unavailable",
    verified: true,
    location: "CBD",
    stats: {
      age: 24,
      height: "165cm",
      weight: "45kg",
      cup: "B+",
      nationality: "Chinese",
    },
    image: "/images/girls/yumo/3.webp",
    description: {
      en: "Radiant and naturally stunning, Yumo is a 2002-born university undergraduate in CBD Auckland. A 'Girl Next Door' with hidden talents in piano, calligraphy, and dance, she offers a rare blend of elegance and athletic flexibility. 100% natural and freshly available, she is known for her exceptional cooperation and sweet personality. Don't miss this limited-time opportunity to meet her.",
      cn: "优点：颜值在线，甜妹，大学本科生在读🎓。钢琴🎹、书法、舞蹈💃、一字马，全身天然无科技。初下💦不久，绝对配合度极高，系邻家妹妹🤤。短期还在等什么🫶",
    },
    price: "$400 / 1h · $300 / 30min",
    services: {
      en: [
        "Bath\u00A0together",
        "Natural\u00A0BJ",
        "Full-body\u00A0slide",
        "69",
        "S-kiss",
        "Finger\u00A0slide",
        "Stockings",
        "Shower\u00A0BJ",
        "Massage",
        "2\u00A0shots",
        "Extra: Come\u00A0in\u00A0mouth (+$50)",
      ],
      cn: [
        "共浴",
        "无套口",
        "全身漫游",
        "69",
        "蛇吻",
        "指滑",
        "丝袜",
        "水中萧",
        "按摩",
        "第2次",
        "额外: 口爆(+$50)",
      ],
    },
    gallery: [
      "/images/girls/yumo/3.webp",
      "/images/girls/yumo/2.webp",
      "/images/girls/yumo/1.webp",
      "/images/girls/yumo/4.webp",
      "/images/girls/yumo/5.webp",
    ],},
  {id: 25,
    name: { en: "May", cn: "May" },
    status: "available",
    verified: true,
    location: "North",
    stats: {
      age: "28+",
      height: "162cm",
      weight: "46kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/may/1.webp",
    description: {
      en: "Sweet and adventurous, May is a stunning companion now available on the North Shore. Known for her petite frame and natural C-cup figure, she offers a playful yet intimate experience. She is highly accommodating and specializes in sensory interactions like romantic 'S-kiss' and multiple rounds. For those seeking a more adventurous session, she also offers 'Back Garden' (Anal) services and a premium VIP package for the complete indulgence.",
      cn: "甜蜜动人、活泼大方，May 现已来到北岸为您提供贴心相伴。她身材娇小均衡，拥有诱人的 C 杯曲线。May 以温柔的性格和极高的配合度著称，擅长细腻的感官互动，如舌吻和双倍云雨体验（可2次）。对于追求极致刺激的朋友，她还提供‘后花园’特殊服务，以及涵盖多项顶级体验的 VIP 奢华套餐，为您开启全方位的感官盛宴。",
    },
    price: "$300 / 1h (VIP) · $220 / 1h · $180 / 30min",
    services: {
      en: [
        "Shower\u00A0together",
        "69",
        "BJ",
        "Massage",
        "French\u00A0kiss",
        "2\u00A0rounds",
        "Extra: Natural\u00A0BJ (+$20) Come\u00A0in\u00A0mouth (+$40) Rimming (+$40) Anal (+$150)",
        "VIP: Natural\u00A0BJ, French\u00A0kiss, 69, Come\u00A0in\u00A0mouth, Rimming, 2\u00A0rounds",
      ],
      cn: [
        "舌吻",
        "洗澡",
        "69",
        "带套口",
        "2次",
        "额外: 后花园(+$150) 无套吹(+$20) 口报(+$40) 毒龙(+$40)",
        "VIP: 无套口/口报/毒龙",
      ],
    },
    gallery: [
      "/images/girls/may/1.webp",
      "/images/girls/may/2.webp",
      "/images/girls/may/3.webp",
      "/images/girls/may/4.webp",
      "/images/girls/may/5.webp",
      "/images/girls/may/6.webp",
      "/images/girls/may/7.webp",
    ],},
  {id: 26,
    name: { en: "Dajie", cn: "大姐" },
    status: "available",
    verified: true,
    location: "Central",
    stats: {
      age: "33+",
      height: "170cm",
      weight: "47kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/dajie/1.webp",
    description: {
      en: "Mature and professional, Dajie is a tall (170cm) and elegant companion serving Central Auckland. She specializes in 'Zhua Long Jin' (specialized prostate and tantric massage), delivering a session that is both therapeutic and deeply pleasurable. Her mature energy and thorough service ensure a refined and satisfying experience. Her VIP package offers extended indulgence with a suite of sensory interactions and multiple rounds for those seeking the ultimate escape.",
      cn: "成熟稳重、技术纯熟，大姐身高 170cm，为您在中区提供极具深度的身心呵护。她尤其擅长‘抓龙筋’这项专业的男性保健按摩，能为您带来前所未有的舒压与愉悦体验。大姐以成熟的风韵和无微不至的服务著称，无论是标准的单次圆满，还是涵盖舌吻、熊推、漫游及多次陪伴（多次）的 VIP 尊享套餐，她都能以细腻的技巧让您流连忘返。",
    },
    price: "$250 / 1h (VIP) · $170 / 1h · $140 / 30min",
    services: {
      en: [
        "BJ",
        "Shower\u00A0together",
        "French\u00A0kiss",
        "Stockings",
        "1\u00A0shot",
        "VIP: Natural\u00A0BJ, Come\u00A0in\u00A0mouth, 69, 2\u00A0rounds",
      ],
      cn: [
        "蛇吻",
        "抓龙筋 (专业按摩)",
        "69",
        "戴套口",
        "爱1次",
        "VIP: 舌吻 洗澡 胸推 漫游 按摩 无套口 69 口爆 多次",
      ],
    },
    gallery: [
      "/images/girls/dajie/1.webp",
      "/images/girls/dajie/2.webp",
      "/images/girls/dajie/3.webp",
      "/images/girls/dajie/4.webp",
      "/images/girls/dajie/5.webp",
      "/images/girls/dajie/6.webp",
      "/images/girls/dajie/7.webp",
    ],},
  {id: 27,
    name: { en: "Shanshan", cn: "珊珊" },
    status: "leave",
    verified: true,
    location: "East",
    stats: {
      age: "33+",
      height: "168cm",
      weight: "45kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/shanshan/1.webp",
    description: {
      en: "Radiant and highly accommodating, Shanshan is a standout beauty now serving East Auckland. With her impressive height of 168cm and natural C-cup figure, she provides an intimate experience focused on service quality. She specializes in 'Zhua Long Jin' (Tantric massage) and offers a deeply sensory journey. For those seeking the ultimate connection, she is one of the few companions offering 'Unprotected Finish' options within her premium VIP package, alongside multiple rounds and oral interactions.",
      cn: "珊珊现已来到东区，为您带来专业且高配合度的私密陪伴。她身高 168cm，身材曼妙平衡（C杯），以卓越的服务态度深受好评。珊珊不仅擅长‘抓龙筋’等专业按摩理疗，更通过细腻的感官互动带您领略不一样的舒缓体验。作为极富冒险精神的女神，她在 VIP 尊享套餐中特别提供‘可无套圆满’（无套🍑）选项，结合多次陪伴和唇齿间的温存，为您打造真正极致的解压时光。",
    },
    price: "$250 / 1h (VIP) · $170 / 1h",
    services: {
      en: [
        "Deep\u00A0kiss",
        "Prostate\u00A0massage",
        "69",
        "BJ (condom)",
        "1\u00A0shot",
        "VIP: S-kiss Bath\u00A0together Breast\u00A0massage Body\u00A0slide Sensory\u00A0massage Natural\u00A0BJ 69 Come\u00A0in\u00A0mouth Multiple\u00A0rounds Natural\u00A0finish",
      ],
      cn: [
        "接吻",
        "抓龙筋 (专业按摩)",
        "69",
        "戴套口",
        "爱1次",
        "VIP: 舌吻 一起洗澡 胸推漫游 感官按摩 无套口 69 口爆 多次 可无套",
      ],
    },
    gallery: [
      "/images/girls/shanshan/1.webp",
      "/images/girls/shanshan/2.webp",
      "/images/girls/shanshan/3.webp",
      "/images/girls/shanshan/4.webp",
      "/images/girls/shanshan/5.webp",
    ],},
  {id: 29,
    name: { en: "Er-er", cn: "二二" },
    status: "leave",
    verified: true,
    location: "Central",
    stats: {
      age: 24,
      height: "163cm",
      weight: "47kg",
      cup: "C (Natural)",
      nationality: "Chinese",
    },
    image: "/images/girls/erer/1.webp",
    description: {
      en: "Youthful and energetic, the beautiful 24-year-old Er-er is a stunning beauty from the '00s generation' now serving Central Auckland. Standing at 163cm with a perfectly balanced figure (163cm, 47kg) and a natural C-cup, she specializes in providing a high-participation, sensory-focused experience. Her sessions are characterized by warmth, enthusiasm, and a deep commitment to service quality. For those seeking the ultimate indulgence, her premium VIP package offers multiple rounds, extended interactions, and specialized oral services in a luxurious, relaxed environment.",
      cn: "青春活力00后，身高163cm，体重47kg，身材完美火辣，拥有一对浑圆丰满的自然C罩杯。二二性格活泼开朗，服务态度极佳，配合度百分百。专业定制SVIP与全套互动体验，包含双人淋浴、缠绵舌吻、性感黑丝、胸推漫游、深度无套口及口爆等项目。在中区温馨舒适的私密空间中，为您打造极其舒适、完全放松的欢愉时光。",
    },
    price: "$320 / 1h (VIP) · $240 / 1h · $200 / 30min",
    services: {
      en: [
        "French kiss",
        "Shower together",
        "Sensory massage",
        "69",
        "Body slide",
        "Natural BJ",
        "Multi shots",
        "VIP: Natural BJ · French kiss · 69 · Cum in mouth · Multi shots · Shower together · Body slide",
      ],
      cn: [
        "舌吻",
        "双人洗浴",
        "感官按摩",
        "69",
        "胸推漫游",
        "无套口",
        "多次数",
        "VIP套餐：无套口 · 舌吻 · 69 · 口爆 · 多次数 · 双人洗浴 · 胸推漫游",
      ],
    },
    gallery: [
      "/images/girls/erer/2.webp",
      "/images/girls/erer/3.webp",
      "/images/girls/erer/data1.webp",
      "/images/girls/erer/data2.webp",
    ],},
  {id: 30,
    name: { en: "Zhuzhu", cn: "珠珠" },
    status: "available",
    verified: true,
    location: "Central",
    stats: {
      age: 26,
      height: "163cm",
      weight: "45kg",
      cup: "B-C",
      nationality: "Chinese",
    },
    image: "/images/girls/zhuzhu/1.webp",
    description: {
      en: "Elegance meets youthful charm in Zhuzhu, a delightful member of our '00s generation' collection in Central Auckland. Standing at 163cm with a slim, graceful physique, she focuses on high-quality sensory interaction and attentive service. Whether you choose her standard session or the comprehensive VIP experience (including multiple rounds and specialized oral services), Zhuzhu ensures a memorable and deeply relaxing stay with her smooth, professional touch.",
      cn: "优雅与青春的完美结合。珠珠作为00后新秀，现已在中区为您提供最贴心的服务。她身材纤细（B-C杯），动作轻柔且专业。无论是标准按摩还是包含蛇吻、口报和多次互动的VIP套餐，珠珠都会让您感受到前所未有的放松与愉悦。",
    },
    price: "$300 / 1h (VIP) · $240 / 1h · $180 / 30min",
    services: {
      en: [
        "French\u00A0kiss",
        "Sensory\u00A0massage",
        "69",
        "BJ\u00A0(condom)",
        "1\u00A0shot",
        "VIP: Snake\u00A0kiss, Shower, Breast\u00A0massage, Body\u00A0slide, Natural\u00A0BJ, CIM, Multiple\u00A0rounds",
      ],
      cn: [
        "接吻",
        "感官按摩",
        "69",
        "戴套吹",
        "1次圆满",
        "VIP: 蛇吻, 一起洗澡, 胸推漫游, 无套口, 口报, 多次圆满",
      ],
    },
    gallery: [
      "/images/girls/zhuzhu/1.webp",
      "/images/girls/zhuzhu/2.webp",
      "/images/girls/zhuzhu/3.webp",
      "/images/girls/zhuzhu/4.webp",
    ],},
  {id: 31,
    name: { en: "Michelle", cn: "Michelle" },
    status: "hidden",
    verified: true,
    location: "Central",
    stats: {
      age: 25,
      height: "163cm",
      weight: "45kg",
      cup: "B-C",
      nationality: "Chinese",
    },
    image: "/images/girls/michelle/1.webp",
    description: {
      en: "Stunning and sophisticated, Michelle is a premium addition to our Central Auckland collection. Standing at 163cm with a slim 45kg frame and a natural B-C cup, she specializes in high-quality French kissing and sensory massage. Michelle is known for her graceful presence and exceptional service standards. Her VIP package offers an immersive experience including snake kisses, shower sessions, and multiple premium interactions for the most discerning guests.",
      cn: "顶级佳丽 Michelle。身高 163cm，体重 45kg，身材匀称（B-C杯）。Michelle 以其卓越的服务态度和迷人的法式接吻深受好评。现在她已就位中区，为您带来最尊贵的感官盛宴。VIP 套餐包含蛇吻、鸳鸯浴、胸推漫游等全方位互动服务。",
    },
    price: "$300 / 1h (VIP) · $220 / 1h · $180 / 30min",
    services: {
      en: [
        "French\u00A0kiss",
        "Sensory\u00A0massage",
        "69",
        "BJ\u00A0(condom)",
        "1\u00A0shot",
        "VIP: Snake\u00A0kiss, Shower, Breast\u00A0massage, Body\u00A0slide, Natural\u00A0BJ, CIM, Multiple\u00A0rounds",
      ],
      cn: [
        "接吻",
        "感官按摩",
        "69",
        "戴套吹",
        "1次圆满",
        "VIP: 蛇吻, 一起洗澡, 胸推漫游, 无套口, 口报, 多次圆满",
      ],
    },
    gallery: [
      "/images/girls/michelle/1.webp",
      "/images/girls/michelle/2.webp",
      "/images/girls/michelle/3.webp",
      "/images/girls/michelle/4.webp",
    ],},
  {id: 32,
    name: { en: "Bingbing", cn: "冰冰" },
    status: "available",
    verified: true,
    location: "Central",
    stats: {
      age: 25,
      height: "163cm",
      weight: "45kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/bingbing/1.webp",
    description: {
      en: "Warm and inviting, Bingbing is a beautiful addition to our collection in Central Auckland. Standing at 163cm with a slender 45kg physique and a full C-cup, she specializes in sensory massage and romantic interaction. Whether you prefer a standard session or her comprehensive VIP package—featuring snake kisses, shared showers, and multiple interactions—Bingbing provides a deeply personal and attentive service designed to melt away your stress.",
      cn: "温柔似水，娇艳动人。冰冰拥有 163cm 的高挑身材和完美的 C 杯曲线。她擅长通过感官按摩和温柔互动为您排忧解难。VIP 套餐更包含蛇吻、鸳鸯浴、胸推漫游及多次云雨互动。冰冰现已在中区恭候您的光临，为您开启一段难忘的私密之旅。",
    },
    price: "$300 / 1h (VIP) · $220 / 1h · $180 / 30min",
    services: {
      en: [
        "French\u00A0kiss",
        "Sensory\u00A0massage",
        "69",
        "BJ\u00A0(condom)",
        "1\u00A0shot",
        "VIP: Snake\u00A0kiss, Shower, Breast\u00A0massage, Body\u00A0slide, Natural\u00A0BJ, CIM, Multiple\u00A0rounds",
      ],
      cn: [
        "接吻",
        "感官按摩",
        "69",
        "戴套吹",
        "1次圆满",
        "VIP: 蛇吻, 一起洗澡, 胸推漫游, 无套口, 口报, 多次圆满",
      ],
    },
    gallery: [
      "/images/girls/bingbing/1.webp",
      "/images/girls/bingbing/2.webp",
      "/images/girls/bingbing/3.webp",
      "/images/girls/bingbing/4.webp",
      "/images/girls/bingbing/5.webp",
    ],},
  {id: 33,
    name: { en: "Japanese Girl", cn: "日本妹" },
    status: "hidden",
    verified: true,
    location: "CBD",
    stats: {
      age: 25,
      height: "163cm",
      weight: "45kg",
      cup: "C (Natural)",
      nationality: "Japanese",
    },
    image: "/images/girls/ribemei/2.webp",
    description: {
      en: "Sweet and petite, Japanese Girl (Nihonmei) brings a youthful and playful energy to the CBD. Standing at 163cm with a slender 45kg frame and natural C-cup features, she specializes in attentive, immersive service with a focus on high-quality interaction. Known for her compliance and sweet personality, she offers a comprehensive range of services including French kissing, 69, and multiple shots for a deeply satisfying and premium experience in the heart of Auckland.",
      cn: "日本妹，25岁，身高163cm，体重45kg，自然C杯。性格甜美可人，配合度极高，为您带来全新的感官体验。现已在奥克兰市区就位，主要提供法式热吻、无套口、69、口报等全方位精品服务。支持2次互动，让您尽享丝滑感受。",
    },
    price: "$360 / 1h",
    services: {
      en: [
        "French\u00A0kiss",
        "shower\u00A0together",
        "3P",
        "Natural\u00A0bj",
        "69",
        "CIM",
        "2\u00A0shots",
        "Extra: Discreet\u00A0Photo/Video\u00A0(+$150), Full\u00A0Face\u00A0Photo/Video\u00A0(+$200), Natural\u00A0Love/CIM\u00A0(+$300)",
      ],
      cn: [
        "舌吻",
        "陪浴",
        "3P",
        "无套口",
        "69",
        "口爆",
        "做2次",
        "额外：不露脸拍照录影(+$150), 露脸拍照录影(+$200), 无套内射(+$300)",
      ],
    },
    gallery: [
      "/images/girls/ribemei/2.webp",
      "/images/girls/ribemei/1.webp",
      "/images/girls/ribemei/3.webp",
      "/images/girls/ribemei/4.webp",
      "/images/girls/ribemei/5.webp",
    ],},
  {id: 55,
    name: { en: "Gucci", cn: "Gucci" },
    status: "unavailable",
    verified: true,
    location: "East",
    stats: {
      age: 25,
      height: "165cm",
      weight: "47kg",
      cup: "C",
      nationality: "Chinese",
    },
    image: "/images/girls/gucci/1.webp",
    description: {
      en: "Gentle and highly professional, Gucci is a stunning 25-year-old beauty with a slender 165cm, 47kg frame and natural C-cup curves now serving East Auckland. Known for her sweet personality and exceptionally caring service, she offers standard sessions featuring deep kissing, sensory massage, and 69. Her premium VIP package includes a double round of pleasure, shower play, direct natural BJ, breast/butt roaming, and come-in-mouth finish for the ultimate relaxation.",
      cn: "温柔体贴、服务至上！25岁的 Gucci 拥有 165cm、47kg 的修长苗条身材，天然 C 罩杯性感曲线。她性格温柔甜美，服务极其贴心到位。提供包含深度接吻、感官精油理疗、69互动、戴套口吹和 1 次云雨的标准体验。升级的 $320 VIP 套餐更包含双人洗浴、胸推漫游、深度无套口、口爆及多次数圆满，在东区温馨舒适的私密空间中为您带来前所未有的深度舒压享受。",
    },
    price: "$320 / 1h (VIP) · $240 / 1h · $200 / 30min",
    services: {
      en: [
        "French kiss",
        "Sensory massage",
        "69",
        "BJ (condom)",
        "1 shot",
        "VIP: French kiss · Shower together · Body slide · Sensory massage · Natural BJ · 69 · Come in mouth · Multi shots",
      ],
      cn: [
        "接吻",
        "感官按摩",
        "69",
        "带套口",
        "爱爱一次",
        "VIP套餐：舌吻 · 双人洗浴 · 胸推漫游 · 感官按摩 · 无套口 · 69 · 口爆 · 多次数",
      ],
    },
    gallery: [
      "/images/girls/gucci/1.webp",
      "/images/girls/gucci/2.webp",
      "/images/girls/gucci/3.webp",
      "/images/girls/gucci/4.webp",
      "/images/girls/gucci/5.webp",
      "/images/girls/gucci/data1.webp",
      "/images/girls/gucci/data2.webp",
    ],}
];

export default girls;
